"""G4 Codegen Subgraph schemas — production-grade module agent system."""

from __future__ import annotations

from typing import Any, Literal, TypedDict

from pydantic import BaseModel, Field

# ── Main subgraph state ──────────────────────────────────────────────


class G4CodegenSubgraphState(TypedDict, total=False):
    """State for the G4 Codegen Subgraph (module agent system)."""

    # Input
    job_id: str
    run_mode: str
    execution_mode: str
    g4_model_ir_path: str
    component_specs_dir: str
    construction_ledger_path: str

    # Loaded data
    g4_model_ir: dict[str, Any]
    rag_context: list[dict[str, Any]]
    rag_score: float
    web_context: list[dict[str, Any]]
    web_search_available: bool
    context_decision: str
    runtime_failure_context: dict[str, Any]

    # Planning outputs
    codegen_plan: dict[str, Any]
    geometry_strategy_plan: dict[str, Any]
    code_architecture_plan: dict[str, Any]

    # Module system
    module_contracts: dict[str, Any]
    module_contexts: dict[str, Any]
    module_results: dict[str, Any]
    module_gate_results: dict[str, Any]
    module_repair_results: dict[str, Any]
    layer_gate_results: dict[str, Any]

    # Integration
    static_semantic_scan: dict[str, Any]
    cross_file_hard_gate: dict[str, Any]
    cross_file_llm_gate: dict[str, Any]

    # Interface contracts
    interface_contracts: dict[str, Any]
    global_llm_repair_report: dict[str, Any]
    global_code_repair_report: dict[str, Any]

    # Output
    proposed_patch: dict[str, Any]
    proposed_patch_path: str
    proposed_patch_summary_path: str
    code_module_plan_path: str
    generated_code_dir: str
    g4_codegen_status: str

    # Control
    current_node: str
    codegen_errors: list[str]
    codegen_warnings: list[str]
    retry_count: int


# ── Module Contract ──────────────────────────────────────────────────


class ModuleContract(BaseModel):
    """Contract defining a module's responsibilities and constraints."""

    module_name: str
    module_type: str
    responsibilities: list[str]
    input_ir_paths: list[str]
    output_files: list[str]
    required_symbols: list[str]
    dependencies: list[str]
    forbidden_patterns: list[str]
    hard_gate_names: list[str]
    llm_gate_names: list[str]
    production_required: bool = True


# ── Module Context ───────────────────────────────────────────────────


class ModuleContext(BaseModel):
    """Context passed to a module agent for code generation."""

    module_name: str
    module_contract: dict[str, Any]
    g4_model_ir_subset: dict[str, Any]
    codegen_plan: dict[str, Any]
    geometry_strategy_plan: dict[str, Any]
    code_architecture_plan: dict[str, Any]
    rag_snippets: list[dict[str, Any]] = Field(default_factory=list)
    web_context: list[dict[str, Any]] = Field(default_factory=list)
    geant4_api_rules: list[str] = Field(default_factory=list)
    module_code_example: dict[str, Any] = Field(default_factory=dict)
    interface_context: dict[str, Any] = Field(default_factory=dict)
    context_retrieval_policy: dict[str, Any] = Field(default_factory=dict)
    existing_generated_file_summaries: list[dict[str, Any]] = Field(default_factory=list)
    previous_failures: list[dict[str, Any]] = Field(default_factory=list)
    runtime_failure_context: dict[str, Any] = Field(default_factory=dict)
    run_mode: str = "strict"


# ── Generated Module File ────────────────────────────────────────────


class GeneratedModuleFile(BaseModel):
    """A single file generated by a module agent."""

    path: str
    operation: str = "create_or_replace"
    new_content: str
    generated_by: str
    module_name: str
    rationale: str
    dependencies: list[str] = Field(default_factory=list)
    satisfies: list[str] = Field(default_factory=list)
    risk_notes: list[str] = Field(default_factory=list)
    used_references: list[str] = Field(default_factory=list)


# ── Module Agent Result ──────────────────────────────────────────────


class ModuleAgentResult(BaseModel):
    """Result from a module agent code generation run."""

    module_name: str
    status: Literal["generated", "failed", "repaired"]
    generated_files: list[GeneratedModuleFile]
    repair_attempts: list[dict[str, Any]] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


# ── Module Gate Result ───────────────────────────────────────────────


class ModuleGateResult(BaseModel):
    """Result from a module gate check (hard or LLM)."""

    module_name: str
    gate_type: Literal["hard", "llm"]
    status: Literal["pass", "fail", "skipped"]
    checks: list[dict[str, Any]] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    reviewer_notes: str | None = None
    scorecard: dict[str, Any] = Field(default_factory=dict)


# ── Codegen Plan ─────────────────────────────────────────────────────


class CodegenPlan(BaseModel):
    """Overall code generation plan derived from G4ModelIR."""

    scenario_type: str
    required_modules: list[str]
    module_order: list[str]
    unsupported_features: list[str] = Field(default_factory=list)
    requires_human_confirmation: bool = False
    rationale: str = ""


# ── Geometry Strategy Plan ───────────────────────────────────────────


class GeometryStrategyPlan(BaseModel):
    """Geometry strategy for each component."""

    global_strategy: str = "agent_generated_geometry"
    component_strategies: dict[str, str] = Field(default_factory=dict)
    requires_external_files: list[dict[str, Any]] = Field(default_factory=list)
    unsupported_features: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


# ── Code Architecture Plan ───────────────────────────────────────────


class CodeArchitecturePlan(BaseModel):
    """C++ class structure plan for the G4 project."""

    classes: list[dict[str, Any]] = Field(default_factory=list)
    file_structure: dict[str, list[str]] = Field(default_factory=dict)
    lifecycle_mapping: dict[str, str] = Field(default_factory=dict)
    dependencies: dict[str, list[str]] = Field(default_factory=dict)


# ── Interface Contracts ──────────────────────────────────────────────


class InterfaceContract(BaseModel):
    """Contract for cross-system interfaces."""

    contract_id: str
    source_path: str = ""
    source_type: str = ""
    conversion_required: bool = False
    conversion_status: str = "not_implemented"
    action: str = ""


class InterfaceContracts(BaseModel):
    """All interface contracts for the project."""

    cad_gdml: list[InterfaceContract] = Field(default_factory=list)
    g4_to_tcad: list[InterfaceContract] = Field(default_factory=list)
    tcad_to_spice: list[InterfaceContract] = Field(default_factory=list)
