import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function readStyles() {
  return readFileSync(resolve(process.cwd(), 'src/styles.css'), 'utf8')
}

function readSimulationViewport() {
  return readFileSync(resolve(process.cwd(), 'src/components/SimulationViewport.tsx'), 'utf8')
}

function readWorkbenchShell() {
  return readFileSync(resolve(process.cwd(), 'src/components/WorkbenchShell.tsx'), 'utf8')
}

describe('workbench cockpit styling', () => {
  it('uses the promotional visual system for the agent cockpit shell', () => {
    const css = readStyles()
    const simulationViewport = readSimulationViewport()
    const workbenchShell = readWorkbenchShell()

    expect(css).toMatch(/\.workbench-shell\s*{[^}]*grid-template-columns:\s*minmax\(250px,\s*0\.8fr\)\s*minmax\(0,\s*1\.75fr\)\s*minmax\(330px,\s*0\.95fr\);/s)
    expect(css).toMatch(/\.workbench-shell\s*{[^}]*background:[^}]*radial-gradient/s)
    expect(css).not.toMatch(/body:has\(\.workbench-shell\)\s*{[^}]*overflow:\s*hidden;/s)
    expect(css).toMatch(/body:has\(\.workbench-shell\)\s*{[^}]*overflow-y:\s*auto;/s)
    expect(css).toMatch(/\.workbench-shell\s*{[^}]*min-height:\s*100vh;/s)
    expect(css).not.toMatch(/\.workbench-shell\s*{(?:(?!min-height).)*height:\s*100vh;/s)
    expect(css).not.toMatch(/\.workbench-shell\s*{[^}]*overflow:\s*hidden;/s)
    expect(css).toMatch(/\.agent-status-rail\s*{[^}]*background:[^}]*rgba\(255,\s*255,\s*255,\s*0\.72\)/s)
    expect(css).toMatch(/\.agent-briefing strong\s*{[^}]*font-family:\s*var\(--radagent-promo-font\);/s)
    expect(css).toMatch(/\.artifact-workspace\s*{[^}]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.78\);/s)
    expect(css).toMatch(/\.artifact-file-list button\.selected\s*{[^}]*border-color:\s*rgba\(185,\s*65,\s*56,\s*0\.42\);/s)
    expect(css).toMatch(/\.simulation-viewport\s*{[^}]*background:[^}]*rgba\(255,\s*255,\s*255,\s*0\.66\)/s)
    expect(css).not.toMatch(/\.simulation-viewport\s*{[^}]*background:\s*#11151a/s)
    expect(simulationViewport).toContain('preserveDrawingBuffer: true')
    expect(css).toMatch(/\.status-pill\s*{[^}]*max-width:\s*min\(100%,\s*360px\);/s)
    expect(css).toMatch(/\.status-pill\s*{[^}]*overflow-wrap:\s*anywhere;/s)
    expect(css).toMatch(/\.workflow-console\s*{[^}]*min-width:\s*0;/s)
    expect(css).toMatch(/\.workflow-console\s*{[^}]*overflow:\s*hidden;/s)
    expect(css).toMatch(/\.agent-status-rail\s*{[^}]*grid-template-rows:\s*auto auto minmax\(0,\s*1fr\) auto;/s)
    expect(css).toMatch(/\.copilot-history-window\s*{[^}]*overflow-y:\s*auto;/s)
    expect(css).toMatch(/\.workbench-command-strip\s*{[^}]*display:\s*grid;/s)
    expect(css).toMatch(/\.workbench-command-strip\s*{[^}]*grid-template-rows:\s*auto auto;/s)
    expect(css).toMatch(/\.center-command-top-row\s*{[^}]*grid-template-columns:\s*max-content\s*minmax\(0,\s*1fr\);/s)
    expect(css).toMatch(/\.center-workspace-metrics\s*{[^}]*grid-template-columns:\s*minmax\(92px,\s*116px\)\s*minmax\(112px,\s*156px\);/s)
    expect(css).toMatch(/\.center-quick-actions\.top\s*{[^}]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\);/s)
    expect(css).toMatch(/\.center-quick-actions\.bottom\s*{[^}]*grid-template-columns:\s*repeat\(5,\s*minmax\(0,\s*1fr\)\);/s)
    expect(css).toMatch(/\.center-quick-actions\s*{[^}]*overflow:\s*visible;/s)
    expect(css).toMatch(/@media \(max-width:\s*1060px\)[\s\S]*\.center-command-top-row\s*{[^}]*grid-template-columns:\s*1fr;/s)
    expect(css).toMatch(/@media \(max-width:\s*1060px\)[\s\S]*\.center-workspace-metrics\s*{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\);/s)
    expect(css).toMatch(/@media \(max-width:\s*1060px\)[\s\S]*\.particle-legend-popover\s*{[^}]*left:\s*0;/s)
    expect(css).toMatch(/@media \(max-width:\s*1060px\)[\s\S]*\.particle-legend-popover\s*{[^}]*right:\s*auto;/s)
    expect(css).toMatch(/\.agent-activity-panel\s*{[^}]*max-height:\s*260px;/s)
    expect(css).toMatch(/\.agent-activity-feed\s*{[^}]*overflow-y:\s*auto;/s)
    expect(css).toMatch(/\.timeline-panel\s*{[^}]*max-height:\s*360px;/s)
    expect(css).toMatch(/\.timeline-scroll\s*{[^}]*overflow-y:\s*auto;/s)
    expect(css).toMatch(/\.artifact-workspace\s*{[^}]*height:\s*calc\(100vh - 28px\);/s)
    expect(css).toMatch(/\.artifact-tree\s*{[^}]*overflow-y:\s*auto;/s)
    expect(css).toMatch(/\.artifact-preview-pane\s*{[^}]*overflow:\s*hidden;/s)
    expect(css).toMatch(/\.artifact-preview-pane pre\s*{[^}]*overflow:\s*auto;/s)
    expect(css).toMatch(/\.workflow-direct-panel\s*{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*minmax\(170px,\s*0\.28fr\);/s)
    expect(css).toMatch(/\.phase-track\s*{[^}]*grid-template-columns:\s*repeat\(5,\s*minmax\(0,\s*1fr\)\);/s)
    expect(css).toMatch(/\.workflow-start-button\s*{[^}]*background:\s*linear-gradient\(135deg,\s*#bc4038,\s*#8f302d\);/s)
    expect(css).toMatch(/\.workflow-start-button\.running\s*{[^}]*background:\s*linear-gradient\(135deg,\s*#23785a,\s*#155f45\);/s)
    expect(workbenchShell).not.toContain("command: '/help'")
    expect(workbenchShell).not.toContain("activeInspector: 'help'")
    expect(workbenchShell).not.toContain('simulationPresetGroups')
    expect(workbenchShell).not.toContain('PresetTaskPreview')
    expect(workbenchShell).not.toContain('任务模板')
    expect(workbenchShell).not.toContain('粒子源')
    expect(workbenchShell).not.toContain('屏蔽材料')
    expect(workbenchShell).not.toContain('点击后会先确认，再提交工作流。')
    expect(workbenchShell).not.toContain('绿色表示仿真工作流正在执行。')
    expect(workbenchShell).toContain('workbench-command-strip')
    expect(workbenchShell).toContain('center-command-top-row')
    expect(workbenchShell).toContain('topQuickActions')
    expect(workbenchShell).toContain('bottomQuickActions')
    expect(workbenchShell).toContain('center-quick-actions')
    expect(workbenchShell).toContain('agent-activity-panel')
    expect(workbenchShell).toContain('timeline-scroll')
    expect(workbenchShell).toContain('仿真指令')
    expect(workbenchShell).toContain('确认开始工作流')
    expect(workbenchShell).toContain('暂停工作流')
    expect(workbenchShell).toContain('confirmation-callout')
    expect(workbenchShell).toContain('reviewCallout.primaryLabel')
    expect(workbenchShell).toContain('executeReviewCommand(reviewCallout.primaryCommand)')
  })
})
