"""Geometry Context Codegen — generates geometry context/setup code.

Produces C++ code for setting up the geometry context including
world volume and coordinate system definitions.
"""

from __future__ import annotations

from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState


async def geometry_context_codegen(state: G4CodegenSubgraphState) -> dict[str, Any]:
    """Generate geometry context setup code from Model IR."""
    model_ir = state.get("g4_model_ir", {})
    components = model_ir.get("components", [])
    errors = list(state.get("errors", []))

    # Find world volume
    world = None
    for comp in components:
        if comp.get("component_type") == "world":
            world = comp
            break

    if not world:
        errors.append("geometry_context_codegen: no world volume found")
        return {"errors": errors, "current_node": "geometry_context_codegen"}

    dims = world.get("dimensions", {})
    dx = dims.get("dx", 1000)
    dy = dims.get("dy", 1000)
    dz = dims.get("dz", 1000)

    code = f"""// Geometry Context — auto-generated by RadAgent G4 Codegen
// World volume: {world.get('display_name', 'World')}

#include "G4Box.hh"
#include "G4LogicalVolume.hh"
#include "G4PVPlacement.hh"
#include "G4NistManager.hh"

// World volume dimensions (half-extents in mm)
constexpr double WORLD_DX = {dx};
constexpr double WORLD_DY = {dy};
constexpr double WORLD_DZ = {dz};
"""

    header = f"""// Geometry Context Header — auto-generated
#ifndef GEOMETRY_CONTEXT_HH
#define GEOMETRY_CONTEXT_HH

// World volume half-extents (mm)
constexpr double WORLD_DX = {dx};
constexpr double WORLD_DY = {dy};
constexpr double WORLD_DZ = {dz};

#endif
"""

    return {
        "geometry_context_code": code,
        "geometry_context_header": header,
        "errors": errors,
        "current_node": "geometry_context_codegen",
    }
