"""Code module plan for structured Geant4 code generation."""

from __future__ import annotations

from pydantic import BaseModel, Field


class CodeModulePlan(BaseModel):
    """A single code module to be generated by a codegen node.

    Each module corresponds to exactly one codegen node and produces
    a set of C++ source/header files. Modules declare dependencies
    on other modules and reference components from the G4ModelIR.
    """

    module_name: str = Field(
        ..., min_length=1,
        description="Module name (e.g. 'MaterialRegistry', 'WorldBuilder')",
    )
    module_type: str = Field(
        ..., min_length=1,
        description="Codegen node type that produces this module "
        "(e.g. 'material_registry', 'component_geometry', 'placement')",
    )
    source_files: list[str] = Field(
        default_factory=list,
        description="C++ source files to generate (e.g. ['MaterialRegistry.cc'])",
    )
    header_files: list[str] = Field(
        default_factory=list,
        description="C++ header files to generate (e.g. ['MaterialRegistry.hh'])",
    )
    config_files: list[str] = Field(
        default_factory=list,
        description="Config/macro files (e.g. ['material_config.json', 'run.mac'])",
    )
    depends_on: list[str] = Field(
        default_factory=list,
        description="Module names this module depends on",
    )
    linked_component_ids: list[str] = Field(
        default_factory=list,
        description="Component IDs from G4ModelIR that this module handles",
    )
    linked_material_ids: list[str] = Field(
        default_factory=list,
        description="Material IDs this module references",
    )


class CodeGenerationPlan(BaseModel):
    """Complete code generation plan derived from G4ModelIR.

    Produced by geometry_builder_plan_node and consumed by the
    codegen nodes to generate structured C++ code.
    """

    plan_id: str = Field(
        ..., min_length=1,
        description="Unique plan identifier",
    )
    job_id: str = Field(
        ..., min_length=1,
        description="Job ID this plan belongs to",
    )
    modules: list[CodeModulePlan] = Field(
        ..., min_length=1,
        description="Ordered list of modules to generate",
    )
    assembly_order: list[str] = Field(
        default_factory=list,
        description="Module generation order (respecting dependencies)",
    )
    total_source_files: int = Field(
        default=0, ge=0,
        description="Total number of source files across all modules",
    )
    total_header_files: int = Field(
        default=0, ge=0,
        description="Total number of header files across all modules",
    )


def validate_code_module_plan(
    data: dict,
) -> tuple[CodeModulePlan | None, list[str]]:
    """Validate a code module plan dict."""
    errors: list[str] = []
    try:
        plan = CodeModulePlan.model_validate(data)
    except Exception as exc:
        errors.append(str(exc))
        return None, errors
    return plan, errors


def validate_code_generation_plan(
    data: dict,
) -> tuple[CodeGenerationPlan | None, list[str]]:
    """Validate a complete code generation plan."""
    errors: list[str] = []
    try:
        plan = CodeGenerationPlan.model_validate(data)
    except Exception as exc:
        errors.append(str(exc))
        return None, errors
    return plan, errors
