"""Component geometry codegen — generates per-component Builder.hh/.cc.

For each component in G4ModelIR, generates a builder class that
constructs the G4LogicalVolume. Strictly limited to geometry:
does NOT write materials, source, scoring, or placement.

Placement is the sole responsibility of PlacementManager.
"""

from __future__ import annotations

import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)

# Mapping from geometry_type to G4 solid constructor
_GEOMETRY_MAP: dict[str, str] = {
    "box": "G4Box",
    "tubs": "G4Tubs",
    "cylinder": "G4Tubs",
    "cons": "G4Cons",
    "sphere": "G4Sphere",
    "trd": "G4Trd",
    "trap": "G4Trap",
    "trapezoid": "G4Trap",
    "para": "G4Para",
    "polycone": "G4Polycone",
}


async def component_geometry_codegen(
    state: RadiationAgentState,
) -> dict[str, Any]:
    """Generate Builder.hh/.cc for each component.

    Reads: g4_model_ir (components only)
    Writes: code_modules entries per component
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    if not model_ir.components:
        return {"code_modules": []}

    modules: list[dict[str, Any]] = []

    for comp in model_ir.components:
        class_name = _to_class_name(comp.component_id) + "Builder"

        header = _generate_header(class_name, comp)
        source = _generate_source(class_name, comp)

        modules.append({
            "module_name": class_name,
            "module_type": "component_geometry",
            "source_files": [f"{class_name}.cc"],
            "header_files": [f"{class_name}.hh"],
            "depends_on": ["MaterialRegistry"],
            "linked_component_ids": [comp.component_id],
            "linked_material_ids": [comp.material_id],
            "generated_content": {
                f"{class_name}::{class_name}.hh": header,
                f"{class_name}::{class_name}.cc": source,
            },
        })

    return {"code_modules": modules}


def _to_class_name(component_id: str) -> str:
    """Convert component_id to PascalCase."""
    return "".join(
        word.capitalize() for word in component_id.replace("-", "_").split("_")
    )


def _build_solid_args(comp: Any) -> tuple[str, str]:
    """Return (solid_type, constructor_args) for a component.

    Returns the G4VSolid subclass name and its constructor argument string.
    """
    dims = comp.dimensions
    geometry_type = comp.geometry_type

    if geometry_type in ("box",):
        dx = dims.get("dx", 1000.0)
        dy = dims.get("dy", 1000.0)
        dz = dims.get("dz", 1000.0)
        args = (
            f'"{comp.component_id}_solid", '
            f"{dx / 2.0}*um, {dy / 2.0}*um, {dz / 2.0}*um"
        )
    elif geometry_type in ("tubs", "cylinder"):
        rmin = dims.get("r_min", 0.0)
        rmax = dims.get("r_max", 500.0)
        dz = dims.get("dz", 1000.0)
        sphi = dims.get("s_phi", 0.0)
        dphi = dims.get("d_phi", 360.0)
        args = (
            f'"{comp.component_id}_solid", '
            f"{sphi}*deg, {dphi}*deg, "
            f"{rmin}*um, {rmax}*um, {dz / 2.0}*um"
        )
    elif geometry_type == "cons":
        rmin1 = dims.get("r_min1", 0.0)
        rmax1 = dims.get("r_max1", 500.0)
        rmin2 = dims.get("r_min2", 0.0)
        rmax2 = dims.get("r_max2", 400.0)
        dz = dims.get("dz", 1000.0)
        sphi = dims.get("s_phi", 0.0)
        dphi = dims.get("d_phi", 360.0)
        args = (
            f'"{comp.component_id}_solid", '
            f"{sphi}*deg, {dphi}*deg, "
            f"{dz / 2.0}*um, "
            f"{rmin1}*um, {rmax1}*um, "
            f"{rmin2}*um, {rmax2}*um"
        )
    else:
        # Fallback to box for unsupported types
        dx = dims.get("dx", 1000.0)
        dy = dims.get("dy", 1000.0)
        dz = dims.get("dz", 1000.0)
        args = (
            f'"{comp.component_id}_solid", '
            f"{dx / 2.0}*um, {dy / 2.0}*um, {dz / 2.0}*um"
        )

    solid_type = _GEOMETRY_MAP.get(geometry_type, "G4Box")
    return solid_type, args


def _generate_header(class_name: str, comp: Any) -> str:
    """Generate Builder.hh for a component.

    Builder creates solid + logical volume only.
    Placement is done by PlacementManager.
    """
    return f"""// {class_name}.hh
// Auto-generated by RadAgent component_geometry_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef {class_name.upper()}_HH
#define {class_name.upper()}_HH

#include "G4LogicalVolume.hh"

#include <string>

class {class_name} {{
public:
    explicit {class_name}(const std::string& nameSuffix = "");
    G4LogicalVolume* GetLogicalVolume() const {{ return logical_; }}

private:
    G4LogicalVolume* logical_;
    std::string nameSuffix_;
}};

#endif
"""


def _generate_source(class_name: str, comp: Any) -> str:
    """Generate Builder.cc for a component.

    Only creates solid + logical volume. No placement.
    """
    solid_type, solid_args = _build_solid_args(comp)

    # Evidence comment
    evidence_comment = "\n".join(
        f"// Evidence: {e}" for e in comp.source_evidence
    )

    # Determine which solid headers to include
    solid_includes = _solid_includes(solid_type)

    return f"""// {class_name}.cc
// Auto-generated by RadAgent component_geometry_codegen
// DO NOT EDIT — regenerate from G4ModelIR
{evidence_comment}

#include "{class_name}.hh"
#include "MaterialRegistry.hh"

#include "G4SystemOfUnits.hh"
#include "G4LogicalVolume.hh"
#include "G4NistManager.hh"
{solid_includes}

#include <iostream>

{class_name}::{class_name}(const std::string& nameSuffix)
    : nameSuffix_(nameSuffix)
{{
    auto& matReg = MaterialRegistry::Instance();

    // Create solid
    auto* solid = new {solid_type}({solid_args});

    // Get material from registry
    G4Material* material = matReg.GetMaterial("{comp.material_id}");
    if (!material) {{
        std::cerr << "Error: material '{comp.material_id}' not found in registry"
                  << std::endl;
    }}

    // Create logical volume
    logical_ = new G4LogicalVolume(
        solid, material,
        "{comp.component_id}_logical" + nameSuffix_
    );
}}
"""


def _solid_includes(solid_type: str) -> str:
    """Return the Geant4 include line(s) for a solid type."""
    _SOLID_HEADERS: dict[str, str] = {
        "G4Box": '#include "G4Box.hh"',
        "G4Tubs": '#include "G4Tubs.hh"',
        "G4Cons": '#include "G4Cons.hh"',
        "G4Sphere": '#include "G4Sphere.hh"',
        "G4Trd": '#include "G4Trd.hh"',
        "G4Trap": '#include "G4Trap.hh"',
        "G4Para": '#include "G4Para.hh"',
        "G4Polycone": '#include "G4Polycone.hh"',
    }
    return _SOLID_HEADERS.get(solid_type, '#include "G4Box.hh"')
