"""Component geometry codegen — generates per-component Builder.hh/.cc.

For each component in G4ModelIR, generates a builder class that
constructs the G4LogicalVolume and G4VPhysicalVolume. Strictly
limited to geometry: does NOT write materials, source, or scoring.
"""

from __future__ import annotations

import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)

# Mapping from geometry_type to G4 solid constructor
_GEOMETRY_MAP: dict[str, str] = {
    "box": "G4Box",
    "tubs": "G4Tubs",
    "cons": "G4Cons",
    "sphere": "G4Sphere",
    "trd": "G4Trd",
    "trap": "G4Trap",
    "para": "G4Para",
}


async def component_geometry_codegen(
    state: RadiationAgentState,
) -> dict[str, Any]:
    """Generate Builder.hh/.cc for each component.

    Reads: g4_model_ir (components only)
    Writes: code_modules entries per component
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    modules: list[dict[str, Any]] = []

    for comp in model_ir.components:
        class_name = _to_class_name(comp.component_id) + "Builder"

        header = _generate_header(class_name, comp)
        source = _generate_source(class_name, comp, model_ir)

        modules.append({
            "module_name": class_name,
            "module_type": "component_geometry",
            "source_files": [f"{class_name}.cc"],
            "header_files": [f"{class_name}.hh"],
            "depends_on": ["MaterialRegistry"],
            "linked_component_ids": [comp.component_id],
            "linked_material_ids": [comp.material_id],
            "generated_content": {
                f"{class_name}::{class_name}.hh": header,
                f"{class_name}::{class_name}.cc": source,
            },
        })

    return {"code_modules": modules}


def _to_class_name(component_id: str) -> str:
    """Convert component_id to PascalCase."""
    return "".join(
        word.capitalize() for word in component_id.replace("-", "_").split("_")
    )


def _generate_header(class_name: str, comp: Any) -> str:
    """Generate Builder.hh for a component."""
    return f"""// {class_name}.hh
// Auto-generated by RadAgent component_geometry_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef {class_name.upper()}_HH
#define {class_name.upper()}_HH

#include "G4LogicalVolume.hh"
#include "G4VPhysicalVolume.hh"
#include "G4PVPlacement.hh"
#include <string>

class {class_name} {{
public:
    {class_name}(const std::string& nameSuffix = "");
    G4LogicalVolume* GetLogicalVolume() const {{ return logical_; }}
    G4VPhysicalVolume* Place(G4LogicalVolume* motherLogical);

private:
    G4LogicalVolume* logical_;
    std::string nameSuffix_;
}};

#endif
"""


def _generate_source(class_name: str, comp: Any, model_ir: Any) -> str:
    """Generate Builder.cc for a component."""
    dims = comp.dimensions
    solid_type = _GEOMETRY_MAP.get(comp.geometry_type, "G4Box")

    # Build solid constructor args from dimensions
    if comp.geometry_type == "box":
        dx = dims.get("dx", 1000.0)
        dy = dims.get("dy", 1000.0)
        dz = dims.get("dz", 1000.0)
        solid_args = (
            f'"{comp.component_id}_solid", '
            f"{dx / 2.0}*um, {dy / 2.0}*um, {dz / 2.0}*um"
        )
    elif comp.geometry_type == "tubs":
        rmin = dims.get("r_min", 0.0)
        rmax = dims.get("r_max", 500.0)
        dz = dims.get("dz", 1000.0)
        sphi = dims.get("s_phi", 0.0)
        dphi = dims.get("d_phi", 360.0)
        solid_args = (
            f'"{comp.component_id}_solid", '
            f"{sphi}*deg, {dphi}*deg, "
            f"{rmin}*um, {rmax}*um, {dz / 2.0}*um"
        )
    else:
        # Fallback to box
        dx = dims.get("dx", 1000.0)
        dy = dims.get("dy", 1000.0)
        dz = dims.get("dz", 1000.0)
        solid_args = (
            f'"{comp.component_id}_solid", '
            f"{dx / 2.0}*um, {dy / 2.0}*um, {dz / 2.0}*um"
        )

    # Placement info
    pos = comp.placement.position
    rot = comp.placement.rotation
    pos_str = f"G4ThreeVector({pos[0]}*um, {pos[1]}*um, {pos[2]}*um)"
    rot_str = (
        "nullptr"
        if all(abs(r) < 1e-10 for r in rot)
        else f"new G4RotationMatrix({rot[0]}*deg, {rot[1]}*deg, {rot[2]}*deg)"
    )

    # Evidence comment
    evidence_comment = "\n".join(
        f"// Evidence: {e}" for e in comp.source_evidence
    )

    return f"""// {class_name}.cc
// Auto-generated by RadAgent component_geometry_codegen
// DO NOT EDIT — regenerate from G4ModelIR
{evidence_comment}

#include "{class_name}.hh"
#include "MaterialRegistry.hh"
#include "G4SystemOfUnits.hh"
#include "G4LogicalVolume.hh"
#include "G4PVPlacement.hh"
#include "G4Box.hh"
#include "G4Tubs.hh"
#include "G4RotationMatrix.hh"
#include "G4NistManager.hh"

{class_name}::{class_name}(const std::string& nameSuffix)
    : nameSuffix_(nameSuffix)
{{
    auto& matReg = MaterialRegistry::Instance();

    // Create solid
    auto* solid = new {solid_type}({solid_args});

    // Get material from registry
    G4Material* material = matReg.GetMaterial("{comp.material_id}");

    // Create logical volume
    logical_ = new G4LogicalVolume(
        solid, material,
        "{comp.component_id}_logical" + nameSuffix_
    );
}}

G4VPhysicalVolume* {class_name}::Place(G4LogicalVolume* motherLogical) {{
    auto* placement = new G4PVPlacement(
        {rot_str},
        {pos_str},
        logical_,
        "{comp.component_id}_phys" + nameSuffix_,
        motherLogical,
        false, 0
    );
    return placement;
}}
"""
