"""Material registry codegen — generates MaterialRegistry.hh/.cc.

Reads material specs from G4ModelIR and generates C++ code that
defines all NIST and custom materials. Strictly limited to materials:
does NOT write placement, source, or scoring code.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)


async def material_registry_codegen(state: RadiationAgentState) -> dict[str, Any]:
    """Generate MaterialRegistry.hh/.cc from G4ModelIR.materials.

    Reads: g4_model_ir (materials only)
    Writes: code_modules entry with generated files
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    materials = model_ir.materials
    nist_materials = [m for m in materials if m.classification == "nist"]
    custom_materials = [m for m in materials if m.classification == "custom"]

    # Generate header
    header = _generate_header(nist_materials, custom_materials)

    # Generate source
    source = _generate_source(nist_materials, custom_materials)

    # Generate config JSON
    config = _generate_config(materials)

    return {
        "code_modules": [{
            "module_name": "MaterialRegistry",
            "module_type": "material_registry",
            "source_files": ["MaterialRegistry.cc"],
            "header_files": ["MaterialRegistry.hh"],
            "config_files": ["material_config.json"],
            "depends_on": [],
            "linked_component_ids": [],
            "linked_material_ids": [m.material_id for m in materials],
            "generated_content": {
                "MaterialRegistry::MaterialRegistry.hh": header,
                "MaterialRegistry::MaterialRegistry.cc": source,
                "MaterialRegistry::material_config.json": config,
            },
        }],
    }


def _generate_header(
    nist_materials: list[Any],
    custom_materials: list[Any],
) -> str:
    """Generate MaterialRegistry.hh."""
    nist_decls = "\n".join(
        f"    G4Material* Get{m.nist_name.replace('G4_', '')}() const;"
        for m in nist_materials
    )
    custom_decls = "\n".join(
        f"    G4Material* Define{m.material_id}(G4NistManager* nist);"
        for m in custom_materials
    )
    return f"""// MaterialRegistry.hh
// Auto-generated by RadAgent material_registry_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef MATERIAL_REGISTRY_HH
#define MATERIAL_REGISTRY_HH

#include "G4Material.hh"
#include "G4NistManager.hh"
#include <map>
#include <string>

class MaterialRegistry {{
public:
    static MaterialRegistry& Instance();
    void DefineAllMaterials();

{nist_decls}
{custom_decls}

    G4Material* GetMaterial(const std::string& id) const;

private:
    MaterialRegistry() = default;
    std::map<std::string, G4Material*> registry_;
}};

#endif
"""


def _generate_source(
    nist_materials: list[Any],
    custom_materials: list[Any],
) -> str:
    """Generate MaterialRegistry.cc."""
    nist_inits = "\n".join(
        f"""G4Material* MaterialRegistry::Get{m.nist_name.replace('G4_', '')}() const {{
    auto it = registry_.find("{m.material_id}");
    return (it != registry_.end()) ? it->second : nullptr;
}}"""
        for m in nist_materials
    )

    custom_defs = "\n\n".join(
        _custom_material_def(m) for m in custom_materials
    )

    nist_registrations = "\n".join(
        f'    registry_["{m.material_id}"] = '
        f"nist->FindOrBuildMaterial(\"{m.nist_name}\");"
        for m in nist_materials
    )

    custom_registrations = "\n".join(
        f'    registry_["{m.material_id}"] = '
        f"Define{m.material_id}(nist);"
        for m in custom_materials
    )

    return f"""// MaterialRegistry.cc
// Auto-generated by RadAgent material_registry_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#include "MaterialRegistry.hh"

MaterialRegistry& MaterialRegistry::Instance() {{
    static MaterialRegistry instance;
    return instance;
}}

void MaterialRegistry::DefineAllMaterials() {{
    auto* nist = G4NistManager::Instance();

    // NIST materials
{nist_registrations}

    // Custom materials
{custom_registrations}
}}

{nist_inits}

{custom_defs}

G4Material* MaterialRegistry::GetMaterial(const std::string& id) const {{
    auto it = registry_.find(id);
    return (it != registry_.end()) ? it->second : nullptr;
}}
"""


def _custom_material_def(mat: Any) -> str:
    """Generate a single custom material definition function."""
    elements_list = mat.composition
    elem_adds = "\n".join(
        f'    {mat.material_id}->AddElement(el_{e.element}, {e.fraction});'
        for e in elements_list
    )
    elem_defs = "\n".join(
        f'    G4Element* el_{e.element} = nist->FindOrBuildElement("{e.element}");'
        for e in elements_list
    )

    return f"""G4Material* MaterialRegistry::Define{mat.material_id}(G4NistManager* nist) {{
    // {mat.name}
    // Source: {", ".join(mat.source_evidence) if mat.source_evidence else "N/A"}
{elem_defs}
    auto* {mat.material_id} = new G4Material(
        "{mat.name}",
        {mat.density_g_cm3} * g/cm3,
        {len(elements_list)}
    );
{elem_adds}
    return {mat.material_id};
}}"""


def _generate_config(materials: list[Any]) -> str:
    """Generate material_config.json for reference."""
    config = {
        "materials": [
            {
                "material_id": m.material_id,
                "classification": m.classification,
                "nist_name": m.nist_name if m.classification == "nist" else None,
                "density_g_cm3": m.density_g_cm3,
            }
            for m in materials
        ]
    }
    return json.dumps(config, indent=2, ensure_ascii=False)
