"""Material registry codegen — generates MaterialRegistry.hh/.cc.

Reads material specs from G4ModelIR and generates C++ code that
defines all NIST and custom materials. Strictly limited to materials:
does NOT write placement, source, or scoring code.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)


def _sanitize_cpp_identifier(name: str) -> str:
    """Convert a material_id/nist_name to a valid C++ identifier suffix.

    Examples: G4_Si → Si, G4_AIR → Air, sio2_layer → Sio2Layer
    """
    # Strip G4_ prefix if present
    if name.startswith("G4_"):
        name = name[3:]
    # Convert to PascalCase if snake_case
    parts = name.split("_")
    return "".join(p.capitalize() for p in parts if p)


async def material_registry_codegen(state: RadiationAgentState) -> dict[str, Any]:
    """Generate MaterialRegistry.hh/.cc from G4ModelIR.materials.

    Reads: g4_model_ir (materials only)
    Writes: code_modules entry with generated files
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    materials = model_ir.materials
    if not materials:
        return {"code_modules": []}

    nist_materials = [m for m in materials if m.classification == "nist"]
    custom_materials = [m for m in materials if m.classification == "custom"]

    # Generate header
    header = _generate_header(nist_materials, custom_materials)

    # Generate source
    source = _generate_source(nist_materials, custom_materials)

    # Generate config JSON
    config = _generate_config(materials)

    return {
        "code_modules": [{
            "module_name": "MaterialRegistry",
            "module_type": "material_registry",
            "source_files": ["MaterialRegistry.cc"],
            "header_files": ["MaterialRegistry.hh"],
            "config_files": ["material_config.json"],
            "depends_on": [],
            "linked_component_ids": [],
            "linked_material_ids": [m.material_id for m in materials],
            "generated_content": {
                "MaterialRegistry::MaterialRegistry.hh": header,
                "MaterialRegistry::MaterialRegistry.cc": source,
                "MaterialRegistry::material_config.json": config,
            },
        }],
    }


def _generate_header(
    nist_materials: list[Any],
    custom_materials: list[Any],
) -> str:
    """Generate MaterialRegistry.hh."""
    nist_decls = "\n".join(
        f"    G4Material* Get{_sanitize_cpp_identifier(m.nist_name or m.material_id)}() const;"
        for m in nist_materials
    )
    custom_decls = "\n".join(
        f"    G4Material* Define{_sanitize_cpp_identifier(m.material_id)}(G4NistManager* nist);"
        for m in custom_materials
    )

    # Only add section comments when there are entries
    nist_section = f"    // NIST material accessors\n{nist_decls}" if nist_materials else ""
    custom_section = f"    // Custom material builders\n{custom_decls}" if custom_materials else ""

    sections = [s for s in [nist_section, custom_section] if s]
    methods_block = "\n\n".join(sections)

    return f"""// MaterialRegistry.hh
// Auto-generated by RadAgent material_registry_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef MATERIAL_REGISTRY_HH
#define MATERIAL_REGISTRY_HH

#include "G4Material.hh"
#include "G4NistManager.hh"

#include <map>
#include <string>

class MaterialRegistry {{
public:
    static MaterialRegistry& Instance();
    void DefineAllMaterials();

{methods_block}

    G4Material* GetMaterial(const std::string& id) const;

private:
    MaterialRegistry() = default;
    std::map<std::string, G4Material*> registry_;
}};

#endif
"""


def _generate_source(
    nist_materials: list[Any],
    custom_materials: list[Any],
) -> str:
    """Generate MaterialRegistry.cc."""
    nist_inits = "\n\n".join(
        f"""G4Material* MaterialRegistry::Get{_sanitize_cpp_identifier(
            m.nist_name or m.material_id
        )}() const {{
    auto it = registry_.find("{m.material_id}");
    return (it != registry_.end()) ? it->second : nullptr;
}}"""
        for m in nist_materials
    )

    custom_defs = "\n\n".join(
        _custom_material_def(m) for m in custom_materials
    )

    nist_registrations = "\n".join(
        f'    registry_["{m.material_id}"] = '
        f"nist->FindOrBuildMaterial(\"{m.nist_name}\");"
        for m in nist_materials
    )

    custom_registrations = "\n".join(
        f'    registry_["{m.material_id}"] = '
        f"Define{_sanitize_cpp_identifier(m.material_id)}(nist);"
        for m in custom_materials
    )

    # Build sections conditionally
    nist_block = f"    // NIST materials\n{nist_registrations}" if nist_materials else ""
    custom_block = f"    // Custom materials\n{custom_registrations}" if custom_materials else ""
    define_sections = "\n\n".join(s for s in [nist_block, custom_block] if s)

    # Collect all method implementations
    method_sections = [s for s in [nist_inits, custom_defs] if s]
    methods_block = "\n\n".join(method_sections)

    return f"""// MaterialRegistry.cc
// Auto-generated by RadAgent material_registry_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#include "MaterialRegistry.hh"

#include "G4SystemOfUnits.hh"

#include <vector>

MaterialRegistry& MaterialRegistry::Instance() {{
    static MaterialRegistry instance;
    return instance;
}}

void MaterialRegistry::DefineAllMaterials() {{
    auto* nist = G4NistManager::Instance();

{define_sections}
}}

{methods_block}

G4Material* MaterialRegistry::GetMaterial(const std::string& id) const {{
    auto it = registry_.find(id);
    return (it != registry_.end()) ? it->second : nullptr;
}}
"""


def _custom_material_def(mat: Any) -> str:
    """Generate a single custom material definition function."""
    elements_list = mat.composition or []

    if not elements_list:
        # Defensive: return nullptr for empty composition
        cpp_id = _sanitize_cpp_identifier(mat.material_id)
        warn_msg = f"Warning: material {mat.material_id} has no composition"
        return (
            f"G4Material* MaterialRegistry::Define{cpp_id}("
            f"G4NistManager* /*nist*/) {{\n"
            f"    // {mat.name} — no composition defined\n"
            f'    std::cerr << "{warn_msg}" << std::endl;\n'
            f"    return nullptr;\n"
            f"}}"
        )

    cpp_id = _sanitize_cpp_identifier(mat.material_id)

    elem_defs = "\n".join(
        f'    G4Element* el_{e.element} = nist->FindOrBuildElement("{e.element}");\n'
        f"    if (!el_{e.element}) {{\n"
        f'        std::cerr << "Error: element {e.element} not found" << std::endl;\n'
        f"        return nullptr;\n"
        f"    }}"
        for e in elements_list
    )

    elem_adds = "\n".join(
        f"    mat_{cpp_id}->AddElement(el_{e.element}, {e.fraction});"
        for e in elements_list
    )

    source_str = ", ".join(mat.source_evidence) if mat.source_evidence else "N/A"

    return f"""G4Material* MaterialRegistry::Define{cpp_id}(G4NistManager* nist) {{
    // {mat.name}
    // Source: {source_str}
{elem_defs}
    auto* mat_{cpp_id} = new G4Material(
        "{mat.name}",
        {mat.density_g_cm3} * g/cm3,
        {len(elements_list)}
    );
{elem_adds}
    return mat_{cpp_id};
}}"""


def _generate_config(materials: list[Any]) -> str:
    """Generate material_config.json for reference."""
    config = {
        "materials": [
            {
                "material_id": m.material_id,
                "classification": m.classification,
                "nist_name": m.nist_name if m.classification == "nist" else None,
                "density_g_cm3": m.density_g_cm3,
            }
            for m in materials
        ]
    }
    return json.dumps(config, indent=2, ensure_ascii=False)
