"""Output manager codegen — generates OutputManager.hh/.cc.

Satisfies g4_output_package contract:
  g4_summary.json — run metadata (n_events, beam, physics, timestamp)
  provenance.json — model IR provenance
  run_log.txt     — stdout/stderr capture
  <scoring>.csv   — one CSV per scoring spec (derived from Model IR)

All output fields are derived from Model IR scoring specs —
NO invented fields.
"""

from __future__ import annotations

import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)


def _to_pascal_case(snake_str: str) -> str:
    """Convert snake_case to PascalCase.

    Examples: sensitive_edep → SensitiveEdep, oxide_dose → OxideDose
    """
    return "".join(word.capitalize() for word in snake_str.split("_"))


async def output_manager_codegen(state: RadiationAgentState) -> dict[str, Any]:
    """Generate OutputManager.hh/.cc for run output.

    Reads: g4_model_ir (scoring output formats, components, sources, physics)
    Writes: code_modules entry with full g4_output_package support
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    if not model_ir.scoring:
        return {"code_modules": []}

    header = _generate_header(model_ir)
    source = _generate_source(model_ir)

    return {
        "code_modules": [{
            "module_name": "OutputManager",
            "module_type": "output_manager",
            "source_files": ["OutputManager.cc"],
            "header_files": ["OutputManager.hh"],
            "depends_on": ["ScoringManager"],
            "linked_component_ids": [],
            "linked_material_ids": [],
            "generated_content": {
                "OutputManager::OutputManager.hh": header,
                "OutputManager::OutputManager.cc": source,
            },
        }],
    }


def _generate_header(model_ir: Any) -> str:
    """Generate OutputManager.hh with g4_output_package contract."""
    # Build scoring method declarations using PascalCase names
    scoring_decls: list[str] = []
    for s in model_ir.scoring:
        method_name = f"Write{_to_pascal_case(s.scoring_id)}"
        scoring_decls.append(f"    void {method_name}();")

    scoring_block = "\n".join(scoring_decls)

    return f"""// OutputManager.hh
// Auto-generated by RadAgent output_manager_codegen
// Satisfies g4_output_package contract:
//   g4_summary.json, provenance.json, run_log.txt
//   + one CSV per scoring spec (from Model IR)
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef OUTPUT_MANAGER_HH
#define OUTPUT_MANAGER_HH

#include "G4UserRunAction.hh"
#include "globals.hh"

#include <string>
#include <fstream>
#include <filesystem>
#include <chrono>
#include <ctime>
#include <map>
#include <vector>

class G4Run;

class OutputManager : public G4UserRunAction {{
public:
    static OutputManager& Instance();

    void BeginOfRunAction(const G4Run* run) override;
    void EndOfRunAction(const G4Run* run) override;

    void SetOutputDir(const std::string& dir);
    void SetModelIRId(const std::string& id);
    void SetJobId(const std::string& id);
    void SetPhysicsList(const std::string& plist);

    // g4_output_package output methods
    void WriteG4Summary();
    void WriteProvenance();
    void WriteRunLog();

    // Per-scoring CSV writers (generated from Model IR scoring specs)
{scoring_block}

private:
    OutputManager() = default;

    std::string outputDir_;
    std::string modelIRId_;
    std::string jobId_;
    std::string physicsList_;
    int nEvents_{{0}};

    void OpenCSV(const std::string& filename, const std::string& header);
    void CloseCSV(const std::string& filename);
}};

#endif
"""


def _generate_source(model_ir: Any) -> str:
    """Generate OutputManager.cc with full g4_output_package outputs."""
    # Build per-scoring Write method implementations
    scoring_methods: list[str] = []
    scoring_calls: list[str] = []

    for s in model_ir.scoring:
        quantities = s.quantities
        target = (
            ", ".join(rs.region_component_id for rs in s.region_scores)
            if s.region_scores
            else s.scoring_id
        )
        fmt = s.output_format
        method_name = f"Write{_to_pascal_case(s.scoring_id)}"
        header_cols = ",".join(quantities)

        scoring_methods.append(
            f"void OutputManager::{method_name}() {{\n"
            f"    // Scoring: {s.scoring_id}\n"
            f"    // Target region: {target}\n"
            f"    // Format: {fmt}\n"
            f'    std::ofstream f(outputDir_ + "/{s.scoring_id}.{fmt}");\n'
            f"    if (!f.is_open()) return;\n"
            f'    f << "{header_cols}\\n";\n'
            f"    // Data rows filled by ScoringManager during event processing\n"
            f"    f.close();\n"
            f"}}"
        )

        scoring_calls.append(f"    {method_name}();")

    scoring_method_block = "\n\n".join(scoring_methods)
    scoring_call_block = "\n".join(scoring_calls)

    # Build beam info from source spec
    beam_lines: list[str] = []
    if model_ir.sources and len(model_ir.sources) > 0:
        src = model_ir.sources[0]
        beam_lines.append(
            f'    f << "  \\"beam_particle\\": \\"{src.particle_type}\\",\\n";'
        )
        beam_lines.append(
            f'    f << "  \\"beam_energy_MeV\\": {src.energy.value},\\n";'
        )

    beam_block = "\n".join(beam_lines)

    return f"""// OutputManager.cc
// Auto-generated by RadAgent output_manager_codegen
// Satisfies g4_output_package contract
// DO NOT EDIT — regenerate from G4ModelIR

#include "OutputManager.hh"

#include "G4Run.hh"
#include "G4SystemOfUnits.hh"
#include "ScoringManager.hh"

#include <fstream>
#include <iostream>
#include <filesystem>
#include <chrono>
#include <ctime>
#include <map>
#include <vector>

OutputManager& OutputManager::Instance() {{
    static OutputManager instance;
    return instance;
}}

void OutputManager::SetOutputDir(const std::string& dir) {{
    outputDir_ = dir;
    std::filesystem::create_directories(dir);
}}

void OutputManager::SetModelIRId(const std::string& id) {{ modelIRId_ = id; }}
void OutputManager::SetJobId(const std::string& id) {{ jobId_ = id; }}
void OutputManager::SetPhysicsList(const std::string& plist) {{ physicsList_ = plist; }}

void OutputManager::OpenCSV(const std::string& filename,
                            const std::string& header) {{
    std::ofstream f(outputDir_ + "/" + filename);
    if (f.is_open()) {{
        f << header << "\\n";
        f.close();
    }}
}}

void OutputManager::CloseCSV(const std::string& filename) {{
    // No-op: files are written and closed per flush
    (void)filename;
}}

void OutputManager::BeginOfRunAction(const G4Run* run) {{
    nEvents_ = run->GetNumberOfEventToBeProcessed();

    if (outputDir_.empty()) {{
        outputDir_ = "./output";
    }}
    SetOutputDir(outputDir_);
}}

void OutputManager::EndOfRunAction(const G4Run* run) {{
    nEvents_ = run->GetNumberOfEvent();

    // Trigger scoring output
    ScoringManager::Instance().EndOfRun();

    // g4_output_package outputs
    WriteG4Summary();
    WriteProvenance();
{scoring_call_block}
    WriteRunLog();
}}

void OutputManager::WriteG4Summary() {{
    // g4_summary.json — run metadata from Model IR
    std::ofstream f(outputDir_ + "/g4_summary.json");
    if (!f.is_open()) return;

    auto now = std::chrono::system_clock::now();
    std::time_t now_time = std::chrono::system_clock::to_time_t(now);
    char timestamp[64];
    std::strftime(timestamp, sizeof(timestamp), "%Y-%m-%dT%H:%M:%SZ",
                  std::gmtime(&now_time));

    f << "{{\\n";
    f << "  \\"n_events\\": " << nEvents_ << ",\\n";
{beam_block}
    f << "  \\"physics_list\\": \\"" << physicsList_ << "\\",\\n";
    f << "  \\"model_ir_id\\": \\"" << modelIRId_ << "\\",\\n";
    f << "  \\"job_id\\": \\"" << jobId_ << "\\",\\n";
    f << "  \\"timestamp\\": \\"" << timestamp << "\\"\\n";
    f << "}}\\n";
    f.close();
}}

void OutputManager::WriteProvenance() {{
    // provenance.json — model IR provenance
    std::ofstream f(outputDir_ + "/provenance.json");
    if (!f.is_open()) return;

    auto now = std::chrono::system_clock::now();
    std::time_t now_time = std::chrono::system_clock::to_time_t(now);
    char timestamp[64];
    std::strftime(timestamp, sizeof(timestamp), "%Y-%m-%dT%H:%M:%SZ",
                  std::gmtime(&now_time));

    f << "{{\\n";
    f << "  \\"model_ir_id\\": \\"" << modelIRId_ << "\\",\\n";
    f << "  \\"job_id\\": \\"" << jobId_ << "\\",\\n";
    f << "  \\"geant4_version\\": \\"11.3\\",\\n";
    f << "  \\"physics_list\\": \\"" << physicsList_ << "\\",\\n";
    f << "  \\"timestamp\\": \\"" << timestamp << "\\"\\n";
    f << "}}\\n";
    f.close();
}}

void OutputManager::WriteRunLog() {{
    // run_log.txt — stdout/stderr capture placeholder
    std::ofstream f(outputDir_ + "/run_log.txt");
    if (!f.is_open()) return;
    f << "Run log for job: " << jobId_ << "\\n";
    f << "Events: " << nEvents_ << "\\n";
    f << "Physics: " << physicsList_ << "\\n";
    f << "Model IR: " << modelIRId_ << "\\n";
    f.close();
}}

// ── Per-scoring CSV writers (generated from Model IR scoring specs) ──
{scoring_method_block}
"""
