"""Output manager codegen — generates OutputManager.hh/.cc.

Handles end-of-run output formatting compatible with g4_output_package.
Parameters come from scoring_spec output_format fields.
Does NOT write geometry, materials, source, or scoring code.
"""

from __future__ import annotations

import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)


async def output_manager_codegen(state: RadiationAgentState) -> dict[str, Any]:
    """Generate OutputManager.hh/.cc for run output.

    Reads: g4_model_ir (scoring output formats)
    Writes: code_modules entry
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    if not model_ir.scoring:
        return {"code_modules": []}

    header = _generate_header()
    source = _generate_source(model_ir.scoring)

    return {
        "code_modules": [{
            "module_name": "OutputManager",
            "module_type": "output_manager",
            "source_files": ["OutputManager.cc"],
            "header_files": ["OutputManager.hh"],
            "depends_on": ["ScoringManager"],
            "linked_component_ids": [],
            "linked_material_ids": [],
            "generated_content": {
                "OutputManager::OutputManager.hh": header,
                "OutputManager::OutputManager.cc": source,
            },
        }],
    }


def _generate_header() -> str:
    """Generate OutputManager.hh."""
    return """// OutputManager.hh
// Auto-generated by RadAgent output_manager_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef OUTPUT_MANAGER_HH
#define OUTPUT_MANAGER_HH

#include "G4UserRunAction.hh"
#include <string>
#include <vector>

class OutputManager : public G4UserRunAction {
public:
    static OutputManager& Instance();

    void BeginOfRunAction(const G4Run* run) override;
    void EndOfRunAction(const G4Run* run) override;

    void SetOutputDir(const std::string& dir);
    void RegisterOutput(const std::string& filename);

private:
    OutputManager() = default;
    std::string outputDir_;
    std::vector<std::string> outputFiles_;
};

#endif
"""


def _generate_source(scoring_specs: list[Any]) -> str:
    """Generate OutputManager.cc."""
    output_registrations = "\n".join(
        f'    RegisterOutput("{s.scoring_id}.{s.output_format}");'
        for s in scoring_specs
    )

    file_writes = "\n".join(
        f"        // Write {s.scoring_id} output ({s.output_format})\n"
        f"        // Quantities: {', '.join(s.quantities)}"
        for s in scoring_specs
    )

    return f"""// OutputManager.cc
// Auto-generated by RadAgent output_manager_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#include "OutputManager.hh"
#include "G4Run.hh"
#include "G4SystemOfUnits.hh"
#include "ScoringManager.hh"
#include <fstream>
#include <iostream>
#include <filesystem>

OutputManager& OutputManager::Instance() {{
    static OutputManager instance;
    return instance;
}}

void OutputManager::SetOutputDir(const std::string& dir) {{
    outputDir_ = dir;
    std::filesystem::create_directories(dir);
}}

void OutputManager::RegisterOutput(const std::string& filename) {{
    outputFiles_.push_back(filename);
}}

void OutputManager::BeginOfRunAction(const G4Run* run) {{
    // Register all output files
{output_registrations}

    if (outputDir_.empty()) {{
        outputDir_ = "./output";
    }}
    SetOutputDir(outputDir_);
}}

void OutputManager::EndOfRunAction(const G4Run* run) {{
    // Trigger scoring output
    ScoringManager::Instance().EndOfRun();

    // Generate summary
    std::ofstream summary(outputDir_ + "/run_summary.txt");
    if (summary.is_open()) {{
        summary << "Run Summary\\n";
        summary << "===========\\n";
        summary << "Number of events: " << run->GetNumberOfEvent() << "\\n";
        summary << "Output files:\\n";
        for (const auto& f : outputFiles_) {{
            summary << "  - " << f << "\\n";
        }}
{file_writes}
        summary.close();
    }}
}}
"""
