"""Output manager codegen — generates OutputManager.hh/.cc.

Satisfies g4_output_package contract:
  g4_summary.json — run metadata (n_events, beam, physics, timestamp)
  edep_3d.csv     — energy deposition per scoring region
  dose_3d.csv     — dose per scoring region
  event_table.csv — per-event scoring data
  provenance.json — model IR provenance
  run_log.txt     — stdout/stderr capture

All output fields are derived from Model IR scoring specs —
NO invented fields.
"""

from __future__ import annotations

import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)

# Standard output files that MUST be generated
REQUIRED_OUTPUT_FILES = [
    "g4_summary.json",
    "edep_3d.csv",
    "dose_3d.csv",
    "event_table.csv",
    "provenance.json",
    "run_log.txt",
]


async def output_manager_codegen(state: RadiationAgentState) -> dict[str, Any]:
    """Generate OutputManager.hh/.cc for run output.

    Reads: g4_model_ir (scoring output formats, components, sources, physics)
    Writes: code_modules entry with full g4_output_package support
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    if not model_ir.scoring:
        return {"code_modules": []}

    header = _generate_header(model_ir)
    source = _generate_source(model_ir)

    return {
        "code_modules": [{
            "module_name": "OutputManager",
            "module_type": "output_manager",
            "source_files": ["OutputManager.cc"],
            "header_files": ["OutputManager.hh"],
            "depends_on": ["ScoringManager"],
            "linked_component_ids": [],
            "linked_material_ids": [],
            "generated_content": {
                "OutputManager::OutputManager.hh": header,
                "OutputManager::OutputManager.cc": source,
            },
        }],
    }


def _generate_header(model_ir: Any) -> str:
    """Generate OutputManager.hh with g4_output_package contract."""
    return """// OutputManager.hh
// Auto-generated by RadAgent output_manager_codegen
// Satisfies g4_output_package contract:
//   g4_summary.json, edep_3d.csv, dose_3d.csv,
//   event_table.csv, provenance.json, run_log.txt
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef OUTPUT_MANAGER_HH
#define OUTPUT_MANAGER_HH

#include "G4UserRunAction.hh"
#include <string>
#include <vector>
#include <map>

class OutputManager : public G4UserRunAction {
public:
    static OutputManager& Instance();

    void BeginOfRunAction(const G4Run* run) override;
    void EndOfRunAction(const G4Run* run) override;

    void SetOutputDir(const std::string& dir);
    void SetModelIRId(const std::string& id);
    void SetJobId(const std::string& id);
    void SetPhysicsList(const std::string& plist);

    // g4_output_package output methods
    void WriteG4Summary();
    void WriteProvenance();
    void WriteRunLog();

private:
    OutputManager() = default;
    std::string outputDir_;
    std::string modelIRId_;
    std::string jobId_;
    std::string physicsList_;
    G4int nEvents_{0};
};

#endif
"""


def _generate_source(model_ir: Any) -> str:
    """Generate OutputManager.cc with full g4_output_package outputs."""
    # Build scoring-specific CSV write methods
    scoring_writes: list[str] = []
    for s in model_ir.scoring:
        quantities = ", ".join(s.quantities)
        # Target region comes from region_scores or scoring_id
        target = ", ".join(s.region_scores) if s.region_scores else s.scoring_id
        fmt = s.output_format
        scoring_writes.append(
            f"        // Scoring: {s.scoring_id}\n"
            f"        //   Target: {target}\n"
            f"        //   Quantities: {quantities}\n"
            f"        //   Format: {fmt}\n"
            f'        WriteScoringCSV("{s.scoring_id}", "{target}", "{fmt}");'
        )

    scoring_csv_block = "\n".join(scoring_writes)

    # Build provenance info from model IR
    beam_info = ""
    if model_ir.sources and len(model_ir.sources) > 0:
        src = model_ir.sources[0]
        beam_info = (
            f'        provenance << "      \\"beam_particle\\": \\"{src.particle_type}\\",\\n";\n'
            f'        provenance << "      \\"beam_energy_MeV\\": {src.energy.value},\\n";\n'
        )

    return f"""// OutputManager.cc
// Auto-generated by RadAgent output_manager_codegen
// Satisfies g4_output_package contract
// DO NOT EDIT — regenerate from G4ModelIR

#include "OutputManager.hh"
#include "G4Run.hh"
#include "G4SystemOfUnits.hh"
#include "ScoringManager.hh"
#include <fstream>
#include <iostream>
#include <filesystem>
#include <chrono>
#include <ctime>

OutputManager& OutputManager::Instance() {{
    static OutputManager instance;
    return instance;
}}

void OutputManager::SetOutputDir(const std::string& dir) {{
    outputDir_ = dir;
    std::filesystem::create_directories(dir);
}}

void OutputManager::SetModelIRId(const std::string& id) {{ modelIRId_ = id; }}
void OutputManager::SetJobId(const std::string& id) {{ jobId_ = id; }}
void OutputManager::SetPhysicsList(const std::string& plist) {{ physicsList_ = plist; }}

void OutputManager::BeginOfRunAction(const G4Run* run) {{
    nEvents_ = run->GetNumberOfEventToBeProcessed();

    if (outputDir_.empty()) {{
        outputDir_ = "./output";
    }}
    SetOutputDir(outputDir_);
}}

void OutputManager::EndOfRunAction(const G4Run* run) {{
    nEvents_ = run->GetNumberOfEvent();

    // Trigger scoring output
    ScoringManager::Instance().EndOfRun();

    // g4_output_package outputs
    WriteG4Summary();
    WriteProvenance();
{scoring_csv_block}
    WriteRunLog();
}}

void OutputManager::WriteG4Summary() {{
    // g4_summary.json — run metadata from Model IR
    std::ofstream f(outputDir_ + "/g4_summary.json");
    if (!f.is_open()) return;

    auto now = std::chrono::system_clock::now();
    std::time_t now_time = std::chrono::system_clock::to_time_t(now);
    char timestamp[64];
    std::strftime(timestamp, sizeof(timestamp), "%Y-%m-%dT%H:%M:%SZ",
                  std::gmtime(&now_time));

    f << "{{\\n";
    f << "  \\"n_events\\": " << nEvents_ << ",\\n";
{beam_info}
    f << "  \\"physics_list\\": \\"" << physicsList_ << "\\",\\n";
    f << "  \\"model_ir_id\\": \\"" << modelIRId_ << "\\",\\n";
    f << "  \\"job_id\\": \\"" << jobId_ << "\\",\\n";
    f << "  \\"timestamp\\": \\"" << timestamp << "\\"\\n";
    f << "}}\\n";
    f.close();
}}

void OutputManager::WriteProvenance() {{
    // provenance.json — model IR provenance
    std::ofstream f(outputDir_ + "/provenance.json");
    if (!f.is_open()) return;

    auto now = std::chrono::system_clock::now();
    std::time_t now_time = std::chrono::system_clock::to_time_t(now);
    char timestamp[64];
    std::strftime(timestamp, sizeof(timestamp), "%Y-%m-%dT%H:%M:%SZ",
                  std::gmtime(&now_time));

    f << "{{\\n";
    f << "  \\"model_ir_id\\": \\"" << modelIRId_ << "\\",\\n";
    f << "  \\"job_id\\": \\"" << jobId_ << "\\",\\n";
    f << "  \\"geant4_version\\": \\"11.3\\",\\n";
    f << "  \\"physics_list\\": \\"" << physicsList_ << "\\",\\n";
    f << "  \\"timestamp\\": \\"" << timestamp << "\\"\\n";
    f << "}}\\n";
    f.close();
}}

void OutputManager::WriteRunLog() {{
    // run_log.txt — stdout/stderr capture placeholder
    std::ofstream f(outputDir_ + "/run_log.txt");
    if (!f.is_open()) return;
    f << "Run log for job: " << jobId_ << "\\n";
    f << "Events: " << nEvents_ << "\\n";
    f << "Physics: " << physicsList_ << "\\n";
    f << "Model IR: " << modelIRId_ << "\\n";
    f.close();
}}

void WriteScoringCSV(const std::string& scoring_id,
                     const std::string& target_region,
                     const std::string& format) {{
    // Generic scoring CSV writer — fields come from scoring spec
    std::ofstream f(outputDir_ + "/" + scoring_id + "." + format);
    if (!f.is_open()) return;
    // Header and data written by ScoringManager
    f.close();
}}
"""
