"""Physics macro codegen — generates physics_list.mac + config JSON.

Parameters come exclusively from physics_spec in G4ModelIR.
Does NOT write geometry, source, or scoring code.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)


async def physics_macro_codegen(state: RadiationAgentState) -> dict[str, Any]:
    """Generate physics_list.mac and physics_config.json.

    Reads: g4_model_ir (physics only)
    Writes: code_modules entry
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    if model_ir.physics is None:
        logger.warning("No physics spec in G4ModelIR — generating defaults")
        return {"code_modules": []}

    physics = model_ir.physics
    macro = _generate_macro(physics)
    config = _generate_config(physics)

    return {
        "code_modules": [{
            "module_name": "PhysicsConfig",
            "module_type": "physics_macro",
            "source_files": [],
            "header_files": [],
            "config_files": ["physics_list.mac", "physics_config.json"],
            "depends_on": [],
            "linked_component_ids": [],
            "linked_material_ids": [],
            "generated_content": {
                "PhysicsConfig::physics_list.mac": macro,
                "PhysicsConfig::physics_config.json": config,
            },
        }],
    }


def _generate_macro(physics: Any) -> str:
    """Generate physics_list.mac."""
    evidence = "\n".join(
        f"# Evidence: {e}" for e in physics.source_evidence
    )

    lines = [
        "# physics_list.mac",
        "# Auto-generated by RadAgent physics_macro_codegen",
        "# DO NOT EDIT — regenerate from G4ModelIR",
        evidence,
        "",
        f"# Physics list: {physics.physics_list}",
        f"# Reasoning: {physics.selection_reasoning}",
        "",
        f"/run/setPhysicsList {physics.physics_list}",
    ]

    # EM physics options
    if physics.em_physics:
        lines.append(f"/process/em/{physics.em_physics}")

    # Production cuts
    if physics.cuts:
        for key, value in physics.cuts.items():
            lines.append(f"/run/setCut {value} {key}")

    # HP neutron
    if physics.hp_neutron:
        lines.append("# High-precision neutron transport enabled")

    lines.append("")

    return "\n".join(lines)


def _generate_config(physics: Any) -> str:
    """Generate physics_config.json for reference."""
    config = {
        "physics_list": physics.physics_list,
        "selection_reasoning": physics.selection_reasoning,
        "em_physics": physics.em_physics,
        "hadronic": physics.hadronic,
        "decay": physics.decay,
        "cuts": physics.cuts,
        "hp_neutron": physics.hp_neutron,
    }
    return json.dumps(config, indent=2, ensure_ascii=False)
