"""Placement codegen — generates PlacementManager.hh/.cc.

Creates all G4PVPlacement calls with checkOverlaps=true.
Parameters come exclusively from component placement specs in G4ModelIR.

This is the SOLE module responsible for placement. Component builders
only create solid + logical volume — they do NOT place.
"""

from __future__ import annotations

import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)


async def placement_codegen(state: RadiationAgentState) -> dict[str, Any]:
    """Generate PlacementManager.hh/.cc with checkOverlaps=true.

    Reads: g4_model_ir (components, placements)
    Writes: code_modules entry
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    if not model_ir.components:
        return {"code_modules": []}

    # Sort components by depth (world first, then children)
    sorted_comps = _sort_by_depth(model_ir)

    header = _generate_header(sorted_comps)
    source = _generate_source(sorted_comps, model_ir)

    return {
        "code_modules": [
            {
                "module_name": "PlacementManager",
                "module_type": "placement",
                "source_files": ["PlacementManager.cc"],
                "header_files": ["PlacementManager.hh"],
                "depends_on": [_to_class_name(c.component_id) + "Builder" for c in sorted_comps],
                "linked_component_ids": [c.component_id for c in sorted_comps],
                "linked_material_ids": [],
                "generated_content": {
                    "PlacementManager::PlacementManager.hh": header,
                    "PlacementManager::PlacementManager.cc": source,
                },
            }
        ],
    }


def _sort_by_depth(model_ir: Any) -> list[Any]:
    """Sort components by tree depth (world first)."""
    depth_map: dict[str, int] = {}
    for comp in model_ir.components:
        depth_map[comp.component_id] = 0

    # BFS to assign depths
    queue = [c.component_id for c in model_ir.components if c.component_type == "world"]
    visited: set[str] = set(queue)

    while queue:
        current = queue.pop(0)
        current_depth = depth_map[current]
        for child in model_ir.components:
            if child.mother_volume == current and child.component_id not in visited:
                depth_map[child.component_id] = current_depth + 1
                visited.add(child.component_id)
                queue.append(child.component_id)

    return sorted(
        model_ir.components,
        key=lambda c: depth_map.get(c.component_id, 0),
    )


def _to_class_name(component_id: str) -> str:
    """Convert component_id to PascalCase."""
    return "".join(word.capitalize() for word in component_id.replace("-", "_").split("_"))


def _generate_header(sorted_comps: list[Any]) -> str:
    """Generate PlacementManager.hh."""
    builder_includes = "\n".join(
        f'#include "{_to_class_name(c.component_id)}Builder.hh"' for c in sorted_comps
    )

    return f"""// PlacementManager.hh
// Auto-generated by RadAgent placement_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef PLACEMENT_MANAGER_HH
#define PLACEMENT_MANAGER_HH

#include "G4LogicalVolume.hh"
#include "G4VPhysicalVolume.hh"
{builder_includes}

class PlacementManager {{
public:
    static PlacementManager& Instance();
    G4VPhysicalVolume* ConstructGeometry();

private:
    PlacementManager() = default;
}};

#endif
"""


def _generate_source(sorted_comps: list[Any], model_ir: Any) -> str:
    """Generate PlacementManager.cc with checkOverlaps=true.

    ALL placements happen here — position/rotation come from
    component placement specs in the IR.
    """
    builder_inits: list[str] = []
    placement_calls: list[str] = []
    builder_map: dict[str, str] = {}

    for comp in sorted_comps:
        class_name = _to_class_name(comp.component_id) + "Builder"
        var_name = f"builder_{comp.component_id.replace('-', '_')}"
        builder_map[comp.component_id] = var_name

        builder_inits.append(f"    auto* {var_name} = new {class_name}();")

        if comp.component_type == "world":
            # World volume gets placed at origin with no rotation
            placement_calls.append(
                f"    // Place world volume\n"
                f"    auto* phys_world = new G4PVPlacement(\n"
                f"        nullptr, G4ThreeVector(),\n"
                f"        {var_name}->GetLogicalVolume(),\n"
                f'        "{comp.component_id}_phys",\n'
                f"        nullptr, false, 0\n"
                f"    );"
            )
        else:
            # Child volume: read position/rotation from IR placement spec
            pos = comp.placement.position
            rot = comp.placement.rotation
            mother_var = builder_map.get(comp.mother_volume or "", "")

            if not mother_var:
                logger.warning(
                    "Component %s has no valid mother_volume '%s'",
                    comp.component_id,
                    comp.mother_volume,
                )
                continue

            pos_str = f"G4ThreeVector({pos[0]}*um, {pos[1]}*um, {pos[2]}*um)"
            if all(abs(r) < 1e-10 for r in rot):
                rot_str = "nullptr"
            else:
                rot_str = f"new G4RotationMatrix({rot[0]}*deg, {rot[1]}*deg, {rot[2]}*deg)"

            placement_calls.append(
                f"    // Place {comp.component_id} in {comp.mother_volume}\n"
                f"    new G4PVPlacement(\n"
                f"        {rot_str}, {pos_str},\n"
                f"        {var_name}->GetLogicalVolume(),\n"
                f'        "{comp.component_id}_phys",\n'
                f"        {mother_var}->GetLogicalVolume(), false, 0\n"
                f"    );"
            )

    # checkOverlaps verification
    check_overlaps = (
        "    // Verify no geometry overlaps\n"
        "    G4PhysicalVolumeStore::GetInstance()->SetCheckOverlaps(true);\n"
        "    for (auto* phys : *G4PhysicalVolumeStore::GetInstance()) {\n"
        "        phys->CheckOverlaps(1000, 0.1 * um, true);\n"
        "    }"
    )

    inits_str = "\n".join(builder_inits)
    places_str = "\n".join(placement_calls)

    return f"""// PlacementManager.cc
// Auto-generated by RadAgent placement_codegen
// DO NOT EDIT — regenerate from G4ModelIR
// checkOverlaps is ALWAYS enabled

#include "PlacementManager.hh"

#include "G4PhysicalVolumeStore.hh"
#include "G4PVPlacement.hh"
#include "G4RotationMatrix.hh"
#include "G4SystemOfUnits.hh"
#include "G4ThreeVector.hh"

PlacementManager& PlacementManager::Instance() {{
    static PlacementManager instance;
    return instance;
}}

G4VPhysicalVolume* PlacementManager::ConstructGeometry() {{
    // Initialize builders
{inits_str}

    // Place all volumes (depth-first order from IR)
{places_str}

{check_overlaps}

    // Return world physical volume
    return (*G4PhysicalVolumeStore::GetInstance())[0];
}}
"""
