"""Scoring codegen — generates ScoringManager.hh/.cc.

Parameters come exclusively from scoring_spec in G4ModelIR.
Does NOT write geometry, materials, or source code.
"""

from __future__ import annotations

import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)


async def scoring_codegen(state: RadiationAgentState) -> dict[str, Any]:
    """Generate ScoringManager.hh/.cc from scoring specs.

    Reads: g4_model_ir (scoring only)
    Writes: code_modules entry
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    if not model_ir.scoring:
        return {"code_modules": []}

    header = _generate_header(model_ir.scoring)
    source = _generate_source(model_ir.scoring, model_ir)

    return {
        "code_modules": [
            {
                "module_name": "ScoringManager",
                "module_type": "scoring",
                "source_files": ["ScoringManager.cc"],
                "header_files": ["ScoringManager.hh"],
                "depends_on": ["SensitiveDetectorManager"],
                "linked_component_ids": [],
                "linked_material_ids": [],
                "generated_content": {
                    "ScoringManager::ScoringManager.hh": header,
                    "ScoringManager::ScoringManager.cc": source,
                },
            }
        ],
    }


def _generate_header(scoring_specs: list[Any]) -> str:
    """Generate ScoringManager.hh."""
    scorer_decls = "\n".join(f"    void Setup{_safe_name(s.scoring_id)}();" for s in scoring_specs)

    return f"""// ScoringManager.hh
// Auto-generated by RadAgent scoring_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef SCORING_MANAGER_HH
#define SCORING_MANAGER_HH

#include "G4VSensitiveDetector.hh"
#include <string>
#include <vector>

class ScoringManager {{
public:
    static ScoringManager& Instance();
    void SetupAllScorers();
    void EndOfRun();

{scorer_decls}

private:
    ScoringManager() = default;
    std::vector<std::string> outputFiles_;
}};

#endif
"""


def _generate_source(
    scoring_specs: list[Any],
    model_ir: Any,
) -> str:
    """Generate ScoringManager.cc."""
    setup_calls = "\n".join(f"    Setup{_safe_name(s.scoring_id)}();" for s in scoring_specs)

    setup_methods = "\n\n".join(_scorer_method(s, model_ir) for s in scoring_specs)

    return f"""// ScoringManager.cc
// Auto-generated by RadAgent scoring_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#include "ScoringManager.hh"
#include "G4AnalysisManager.hh"
#include "G4SystemOfUnits.hh"
#include <fstream>
#include <iostream>

ScoringManager& ScoringManager::Instance() {{
    static ScoringManager instance;
    return instance;
}}

void ScoringManager::SetupAllScorers() {{
    auto* analysisManager = G4AnalysisManager::Instance();
    analysisManager->SetVerboseLevel(1);
{setup_calls}
}}

void ScoringManager::EndOfRun() {{
    auto* analysisManager = G4AnalysisManager::Instance();
    analysisManager->Write();
    analysisManager->CloseFile();
}}

{setup_methods}
"""


def _scorer_method(spec: Any, model_ir: Any) -> str:
    """Generate setup method for a single scoring spec."""
    name = _safe_name(spec.scoring_id)

    if spec.scoring_type == "voxel" and spec.voxel_grid:
        voxel = spec.voxel_grid
        vs = voxel.voxel_size
        return f"""void ScoringManager::Setup{name}() {{
    // Voxel scoring: {spec.scoring_id}
    // Target: {voxel.target_component_id}
    // Voxel size: [{vs[0]}, {vs[1]}, {vs[2]}] um
    auto* analysisManager = G4AnalysisManager::Instance();
    analysisManager->OpenFile("{spec.scoring_id}");
    // Voxel mesh setup would go here
    // Quantities: {", ".join(spec.quantities)}
    outputFiles_.push_back("{spec.scoring_id}.{spec.output_format}");
}}"""

    elif spec.scoring_type == "region" and spec.region_scores:
        regions = "; ".join(
            f"{rs.region_component_id} -> {rs.quantity}" for rs in spec.region_scores
        )
        return f"""void ScoringManager::Setup{name}() {{
    // Region scoring: {spec.scoring_id}
    // Regions: {regions}
    // Quantities: {", ".join(spec.quantities)}
    auto* analysisManager = G4AnalysisManager::Instance();
    analysisManager->OpenFile("{spec.scoring_id}");
    // Region scoring hooks would go here
    outputFiles_.push_back("{spec.scoring_id}.{spec.output_format}");
}}"""

    return f"""void ScoringManager::Setup{name}() {{
    // Generic scoring: {spec.scoring_id}
    // Quantities: {", ".join(spec.quantities)}
}}"""


def _safe_name(scoring_id: str) -> str:
    """Convert scoring_id to safe method name suffix."""
    return "".join(word.capitalize() for word in scoring_id.replace("-", "_").split("_"))
