"""Sensitive detector codegen — generates SD manager and Hit classes.

Parameters come exclusively from sensitive_detector_spec in G4ModelIR.
Does NOT write geometry, materials, or scoring code.
"""

from __future__ import annotations

import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)


async def sensitive_detector_codegen(
    state: RadiationAgentState,
) -> dict[str, Any]:
    """Generate SensitiveDetectorManager.hh/.cc and Hit.hh/.cc.

    Reads: g4_model_ir (sensitive_detectors only)
    Writes: code_modules entry
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    if not model_ir.sensitive_detectors:
        return {"code_modules": []}

    hit_header = _generate_hit_header()
    hit_source = _generate_hit_source(model_ir.sensitive_detectors)
    sd_header = _generate_sd_header(model_ir.sensitive_detectors)
    sd_source = _generate_sd_source(model_ir.sensitive_detectors)

    comp_ids: list[str] = []
    for sd in model_ir.sensitive_detectors:
        comp_ids.extend(sd.linked_component_ids)

    return {
        "code_modules": [{
            "module_name": "SensitiveDetectorManager",
            "module_type": "sensitive_detector",
            "source_files": ["SensitiveDetectorManager.cc", "Hit.cc"],
            "header_files": ["SensitiveDetectorManager.hh", "Hit.hh"],
            "depends_on": [],
            "linked_component_ids": sorted(set(comp_ids)),
            "linked_material_ids": [],
            "generated_content": {
                "SensitiveDetectorManager::Hit.hh": hit_header,
                "SensitiveDetectorManager::Hit.cc": hit_source,
                "SensitiveDetectorManager::SensitiveDetectorManager.hh": sd_header,
                "SensitiveDetectorManager::SensitiveDetectorManager.cc": sd_source,
            },
        }],
    }


def _generate_hit_header() -> str:
    """Generate Hit.hh with standard radiation hit fields."""
    return """// Hit.hh
// Auto-generated by RadAgent sensitive_detector_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef HIT_HH
#define HIT_HH

#include "G4VHit.hh"
#include "G4THitsCollection.hh"
#include "G4Allocator.hh"
#include "G4ThreeVector.hh"

class Hit : public G4VHit {
public:
    Hit();
    ~Hit() override = default;

    Hit(const Hit& other);
    const Hit& operator=(const Hit& other);

    G4bool operator==(const Hit& other) const;

    inline void* operator new(size_t);
    inline void operator delete(void*);

    // Hit fields
    void SetEventID(G4int id) { fEventID = id; }
    G4int GetEventID() const { return fEventID; }

    void SetTrackID(G4int id) { fTrackID = id; }
    G4int GetTrackID() const { return fTrackID; }

    void SetParticlePDG(G4int pdg) { fParticlePDG = pdg; }
    G4int GetParticlePDG() const { return fParticlePDG; }

    void SetEdep(G4double edep) { fEdep = edep; }
    void AddEdep(G4double edep) { fEdep += edep; }
    G4double GetEdep() const { return fEdep; }

    void SetPosition(G4ThreeVector pos) { fPosition = pos; }
    G4ThreeVector GetPosition() const { return fPosition; }

    void SetTime(G4double t) { fTime = t; }
    G4double GetTime() const { return fTime; }

private:
    G4int fEventID;
    G4int fTrackID;
    G4int fParticlePDG;
    G4double fEdep;
    G4ThreeVector fPosition;
    G4double fTime;
};

typedef G4THitsCollection<Hit> HitsCollection;
extern G4ThreadLocal G4Allocator<Hit>* HitAllocator;

inline void* Hit::operator new(size_t) {
    if (!HitAllocator) HitAllocator = new G4Allocator<Hit>;
    return (void*)HitAllocator->AllocSingleObject();
}

inline void Hit::operator delete(void* hit) {
    HitAllocator->FreeSingleObject((Hit*)hit);
}

#endif
"""


def _generate_hit_source(sds: list[Any]) -> str:
    """Generate Hit.cc."""
    return """// Hit.cc
// Auto-generated by RadAgent sensitive_detector_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#include "Hit.hh"
#include "G4SystemOfUnits.hh"

G4ThreadLocal G4Allocator<Hit>* HitAllocator = nullptr;

Hit::Hit()
    : G4VHit(),
      fEventID(-1), fTrackID(-1), fParticlePDG(0),
      fEdep(0.), fTime(0.) {}

Hit::Hit(const Hit& other)
    : G4VHit() {
    fEventID = other.fEventID;
    fTrackID = other.fTrackID;
    fParticlePDG = other.fParticlePDG;
    fEdep = other.fEdep;
    fPosition = other.fPosition;
    fTime = other.fTime;
}

const Hit& Hit::operator=(const Hit& other) {
    fEventID = other.fEventID;
    fTrackID = other.fTrackID;
    fParticlePDG = other.fParticlePDG;
    fEdep = other.fEdep;
    fPosition = other.fPosition;
    fTime = other.fTime;
    return *this;
}

G4bool Hit::operator==(const Hit& other) const {
    return (this == &other) ? true : false;
}
"""


def _generate_sd_header(sds: list[Any]) -> str:
    """Generate SensitiveDetectorManager.hh."""
    sd_decls = "\n".join(
        f"    void Attach{sd.sd_id.replace('-', '_').title().replace('_', '')}"
        f"(G4LogicalVolume* lv);"
        for sd in sds
    )

    return f"""// SensitiveDetectorManager.hh
// Auto-generated by RadAgent sensitive_detector_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef SENSITIVE_DETECTOR_MANAGER_HH
#define SENSITIVE_DETECTOR_MANAGER_HH

#include "G4VSensitiveDetector.hh"
#include "Hit.hh"
#include <map>
#include <string>

class SensitiveDetectorManager {{
public:
    static SensitiveDetectorManager& Instance();
    void AttachAll(G4LogicalVolume* worldLogical);

{sd_decls}

private:
    SensitiveDetectorManager() = default;
    std::map<std::string, G4VSensitiveDetector*> detectors_;
}};

#endif
"""


def _generate_sd_source(sds: list[Any]) -> str:
    """Generate SensitiveDetectorManager.cc."""
    attach_methods = "\n\n".join(
        _attach_method(sd) for sd in sds
    )

    attach_calls = "\n".join(
        f"    Attach{sd.sd_id.replace('-', '_').title().replace('_', '')}"
        f"(worldLogical);"
        for sd in sds
    )

    return f"""// SensitiveDetectorManager.cc
// Auto-generated by RadAgent sensitive_detector_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#include "SensitiveDetectorManager.hh"
#include "G4LogicalVolume.hh"
#include "G4SDManager.hh"

SensitiveDetectorManager& SensitiveDetectorManager::Instance() {{
    static SensitiveDetectorManager instance;
    return instance;
}}

void SensitiveDetectorManager::AttachAll(G4LogicalVolume* worldLogical) {{
{attach_calls}
}}

{attach_methods}
"""


def _attach_method(sd: Any) -> str:
    """Generate a single attach method for a sensitive detector."""
    method_name = (
        f"Attach{sd.sd_id.replace('-', '_').title().replace('_', '')}"
    )
    collection = sd.collection_name

    return f"""void SensitiveDetectorManager::{method_name}(G4LogicalVolume* lv) {{
    auto* sdManager = G4SDManager::GetSDMpointer();
    auto* sd = new G4VSensitiveDetector("{sd.name}", "{collection}");
    sdManager->AddNewDetector(sd);
    lv->SetSensitiveDetector(sd);
    detectors_["{sd.sd_id}"] = sd;
}}"""
