"""Sensitive detector codegen — generates SD manager and Hit classes.

Parameters come exclusively from sensitive_detector_spec in G4ModelIR.
Does NOT write geometry, materials, or scoring code.

Each SD spec defines:
  - Which components to attach to (linked_component_ids)
  - Which hit fields to record (hit_fields)
  - Collection name for G4HC
"""

from __future__ import annotations

import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)


def _sanitize_method_name(sd_id: str) -> str:
    """Convert sd_id to a PascalCase method suffix.

    Examples: sensor_sd → SensorSd, oxide_detector → OxideDetector
    """
    return "".join(
        word.capitalize() for word in sd_id.replace("-", "_").split("_")
    )


async def sensitive_detector_codegen(
    state: RadiationAgentState,
) -> dict[str, Any]:
    """Generate SensitiveDetectorManager.hh/.cc and Hit.hh/.cc.

    Reads: g4_model_ir (sensitive_detectors only)
    Writes: code_modules entry
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    if not model_ir.sensitive_detectors:
        return {"code_modules": []}

    hit_header = _generate_hit_header(model_ir.sensitive_detectors)
    hit_source = _generate_hit_source(model_ir.sensitive_detectors)
    sd_header = _generate_sd_header(model_ir.sensitive_detectors)
    sd_source = _generate_sd_source(model_ir.sensitive_detectors, model_ir)

    comp_ids: list[str] = []
    for sd in model_ir.sensitive_detectors:
        comp_ids.extend(sd.linked_component_ids)

    return {
        "code_modules": [{
            "module_name": "SensitiveDetectorManager",
            "module_type": "sensitive_detector",
            "source_files": ["SensitiveDetectorManager.cc", "Hit.cc"],
            "header_files": ["SensitiveDetectorManager.hh", "Hit.hh"],
            "depends_on": [],
            "linked_component_ids": sorted(set(comp_ids)),
            "linked_material_ids": [],
            "generated_content": {
                "SensitiveDetectorManager::Hit.hh": hit_header,
                "SensitiveDetectorManager::Hit.cc": hit_source,
                "SensitiveDetectorManager::SensitiveDetectorManager.hh": sd_header,
                "SensitiveDetectorManager::SensitiveDetectorManager.cc": sd_source,
            },
        }],
    }


def _generate_hit_header(sds: list[Any]) -> str:
    """Generate Hit.hh with fields from IR hit_fields.

    Always includes standard fields (eventID, trackID, edep, position, time)
    plus any additional fields defined in the SD specs.
    """
    # Collect all unique extra fields across all SDs
    extra_fields: list[tuple[str, str]] = []
    seen: set[str] = set()
    for sd in sds:
        for hf in sd.hit_fields:
            if hf.name not in seen and hf.name not in (
                "event_id", "track_id", "edep_MeV", "position", "time"
            ):
                seen.add(hf.name)
                cpp_type = _field_type_to_cpp(hf.dtype)
                extra_fields.append((hf.name, cpp_type))

    # Generate setter/getter pairs for extra fields
    extra_accessors = "\n".join(
        f"    void Set{_to_pascal(fname)}({ctype} v) {{ f{_to_pascal(fname)} = v; }}\n"
        f"    {ctype} Get{_to_pascal(fname)}() const {{ return f{_to_pascal(fname)}; }}"
        for fname, ctype in extra_fields
    )

    extra_members = "\n".join(
        f"    {ctype} f{_to_pascal(fname)};"
        for fname, ctype in extra_fields
    )

    # Initialize extra fields in constructor
    extra_inits = ", ".join(
        f"f{_to_pascal(fname)}(0)"
        for fname, _ in extra_fields
    )
    init_prefix = ", " if extra_inits else ""

    return f"""// Hit.hh
// Auto-generated by RadAgent sensitive_detector_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef HIT_HH
#define HIT_HH

#include "G4VHit.hh"
#include "G4THitsCollection.hh"
#include "G4Allocator.hh"
#include "G4ThreeVector.hh"

class Hit : public G4VHit {{
public:
    Hit();
    ~Hit() override = default;

    Hit(const Hit& other);
    const Hit& operator=(const Hit& other);

    G4bool operator==(const Hit& other) const;

    inline void* operator new(size_t);
    inline void operator delete(void*);

    // Standard hit fields
    void SetEventID(int id) {{ fEventID = id; }}
    int GetEventID() const {{ return fEventID; }}

    void SetTrackID(int id) {{ fTrackID = id; }}
    int GetTrackID() const {{ return fTrackID; }}

    void SetEdep(double edep) {{ fEdep = edep; }}
    void AddEdep(double edep) {{ fEdep += edep; }}
    double GetEdep() const {{ return fEdep; }}

    void SetPosition(G4ThreeVector pos) {{ fPosition = pos; }}
    G4ThreeVector GetPosition() const {{ return fPosition; }}

    void SetTime(double t) {{ fTime = t; }}
    double GetTime() const {{ return fTime; }}

    // Additional fields from SD specs
{extra_accessors}

private:
    int fEventID;
    int fTrackID;
    double fEdep;
    G4ThreeVector fPosition;
    double fTime;
{extra_members}
}};

typedef G4THitsCollection<Hit> HitsCollection;
extern G4ThreadLocal G4Allocator<Hit>* HitAllocator;

inline void* Hit::operator new(size_t) {{
    if (!HitAllocator) HitAllocator = new G4Allocator<Hit>;
    return (void*)HitAllocator->AllocSingleObject();
}}

inline void Hit::operator delete(void* hit) {{
    HitAllocator->FreeSingleObject((Hit*)hit);
}}

#endif
"""


def _generate_hit_source(sds: list[Any]) -> str:
    """Generate Hit.cc."""
    # Collect extra fields for initialization
    extra_fields: list[tuple[str, str]] = []
    seen: set[str] = set()
    for sd in sds:
        for hf in sd.hit_fields:
            if hf.name not in seen and hf.name not in (
                "event_id", "track_id", "edep_MeV", "position", "time"
            ):
                seen.add(hf.name)
                extra_fields.append((hf.name, _field_type_to_cpp(hf.dtype)))

    extra_init_list = ", ".join(
        f"f{_to_pascal(fname)}(0)"
        for fname, _ in extra_fields
    )
    init_prefix = ", " if extra_init_list else ""

    extra_copy = "\n".join(
        f"    f{_to_pascal(fname)} = other.f{_to_pascal(fname)};"
        for fname, _ in extra_fields
    )

    return f"""// Hit.cc
// Auto-generated by RadAgent sensitive_detector_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#include "Hit.hh"

G4ThreadLocal G4Allocator<Hit>* HitAllocator = nullptr;

Hit::Hit()
    : G4VHit(),
      fEventID(-1), fTrackID(-1),
      fEdep(0.), fTime(0.){init_prefix}{extra_init_list} {{}}

Hit::Hit(const Hit& other)
    : G4VHit() {{
    fEventID = other.fEventID;
    fTrackID = other.fTrackID;
    fEdep = other.fEdep;
    fPosition = other.fPosition;
    fTime = other.fTime;
{extra_copy}
}}

const Hit& Hit::operator=(const Hit& other) {{
    fEventID = other.fEventID;
    fTrackID = other.fTrackID;
    fEdep = other.fEdep;
    fPosition = other.fPosition;
    fTime = other.fTime;
{extra_copy}
    return *this;
}}

G4bool Hit::operator==(const Hit& other) const {{
    return (this == &other) ? true : false;
}}
"""


def _generate_sd_header(sds: list[Any]) -> str:
    """Generate SensitiveDetectorManager.hh."""
    # Build per-SD attach methods
    sd_decls = "\n".join(
        f"    void Attach{_sanitize_method_name(sd.sd_id)}"
        f"(G4LogicalVolume* lv);"
        for sd in sds
    )

    return f"""// SensitiveDetectorManager.hh
// Auto-generated by RadAgent sensitive_detector_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef SENSITIVE_DETECTOR_MANAGER_HH
#define SENSITIVE_DETECTOR_MANAGER_HH

#include "G4VSensitiveDetector.hh"
#include "Hit.hh"

#include <map>
#include <string>

class SensitiveDetectorManager {{
public:
    static SensitiveDetectorManager& Instance();
    void AttachAll(G4LogicalVolume* worldLogical);

    // Per-SD attach methods
{sd_decls}

private:
    SensitiveDetectorManager() = default;
    std::map<std::string, G4VSensitiveDetector*> detectors_;
}};

#endif
"""


def _generate_sd_source(sds: list[Any], model_ir: Any) -> str:
    """Generate SensitiveDetectorManager.cc."""
    attach_methods = "\n\n".join(
        _attach_method(sd) for sd in sds
    )

    attach_calls = "\n".join(
        f"    Attach{_sanitize_method_name(sd.sd_id)}(worldLogical);"
        for sd in sds
    )

    return f"""// SensitiveDetectorManager.cc
// Auto-generated by RadAgent sensitive_detector_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#include "SensitiveDetectorManager.hh"

#include "G4LogicalVolume.hh"
#include "G4SDManager.hh"
#include "G4Step.hh"
#include "G4TouchableHistory.hh"
#include "G4SystemOfUnits.hh"

SensitiveDetectorManager& SensitiveDetectorManager::Instance() {{
    static SensitiveDetectorManager instance;
    return instance;
}}

void SensitiveDetectorManager::AttachAll(G4LogicalVolume* worldLogical) {{
{attach_calls}
}}

{attach_methods}
"""


def _attach_method(sd: Any) -> str:
    """Generate a single attach method for a sensitive detector.

    Creates a concrete SD class (not abstract G4VSensitiveDetector!)
    that records hits into the specified collection.
    """
    method_suffix = _sanitize_method_name(sd.sd_id)
    collection = sd.collection_name
    components = sd.linked_component_ids

    # Build component search logic
    if len(components) == 1:
        search = (
            f'    G4LogicalVolume* target = G4LogicalVolumeStore::GetInstance()->'
            f'GetVolume("{components[0]}_logical", false);\n'
            f"    if (!target) return;\n"
        )
    else:
        searches = "\n".join(
            f'    {{\n'
            f'        G4LogicalVolume* target = G4LogicalVolumeStore::GetInstance()->'
            f'GetVolume("{cid}_logical", false);\n'
            f'        if (target) target->SetSensitiveDetector(sd);\n'
            f'    }}'
            for cid in components
        )
        search = searches

    # Build the concrete SD class (simple inner implementation)
    # We create a lightweight SD that records hits into our Hit class
    hit_fill = _build_hit_fill(sd)

    # Generate a concrete SD class per spec
    sd_class_name = f"{method_suffix}SD"

    return f"""void SensitiveDetectorManager::Attach{method_suffix}(G4LogicalVolume* worldLogical) {{
    auto* sdManager = G4SDManager::GetSDMpointer();
    auto* sd = new {sd_class_name}("{sd.name}", "{collection}");
    sdManager->AddNewDetector(sd);
    detectors_["{sd.sd_id}"] = sd;

    // Attach to specific component logical volumes
{search}
}}

// ── Concrete SD class for {sd.name} ──

class {sd_class_name} : public G4VSensitiveDetector {{
public:
    {sd_class_name}(const std::string& name, const std::string& collection)
        : G4VSensitiveDetector(name, collection) {{
        collectionName.insert(collection);
    }}

    void Initialize(G4HCofThisEvent* hitCollection) override {{
        fHitsCollection = new HitsCollection(SensitiveDetectorName, collectionName[0]);
        int hcID = G4SDManager::GetSDMpointer()->GetCollectionID(collectionName[0]);
        hitCollection->AddHitsCollection(hcID, fHitsCollection);
    }}

    G4bool ProcessHits(G4Step* step, G4TouchableHistory*) override {{
        auto* hit = new Hit();
{hit_fill}
        fHitsCollection->insert(hit);
        return true;
    }}

private:
    HitsCollection* fHitsCollection = nullptr;
}};"""


def _build_hit_fill(sd: Any) -> str:
    """Generate the hit field filling code from SD spec."""
    lines = [
        '        hit->SetEventID(G4RunManager::GetRunManager()->GetCurrentEvent()->GetEventID());',
        '        hit->SetTrackID(step->GetTrack()->GetTrackID());',
        '        hit->SetEdep(step->GetTotalEnergyDeposit());',
        '        hit->SetPosition(step->GetPreStepPoint()->GetPosition());',
        '        hit->SetTime(step->GetPreStepPoint()->GetGlobalTime());',
    ]
    return "\n".join(lines)


def _field_type_to_cpp(dtype: str) -> str:
    """Map field dtype to C++ type."""
    mapping = {
        "float": "float",
        "double": "double",
        "int": "int",
        "long": "long",
        "bool": "bool",
    }
    return mapping.get(dtype, "double")


def _to_pascal(name: str) -> str:
    """Convert snake_case name to PascalCase."""
    return "".join(word.capitalize() for word in name.split("_"))
