"""Source codegen — generates PrimaryGeneratorAction.hh/.cc + source.mac.

Parameters come exclusively from source_spec in G4ModelIR.
Does NOT write geometry, materials, or scoring code.
"""

from __future__ import annotations

import logging
from typing import Any

from agent_core.g4_codegen.schemas import G4CodegenSubgraphState as RadiationAgentState

logger = logging.getLogger(__name__)

# PDG encoding map
_PDG_MAP: dict[str, int] = {
    "proton": 2212,
    "neutron": 2112,
    "gamma": 22,
    "e-": 11,
    "e+": -11,
    "positron": -11,
    "electron": 11,
    "mu-": 13,
    "mu+": -13,
    "alpha": 1000020040,
    "pi+": 211,
    "pi-": -211,
}


async def source_codegen(state: RadiationAgentState) -> dict[str, Any]:
    """Generate PrimaryGeneratorAction.hh/.cc and source.mac.

    Reads: g4_model_ir (sources only)
    Writes: code_modules entry
    """
    model_ir_dict = state.get("g4_model_ir", {})

    from agent_core.g4_modeling.schemas.g4_model_ir import G4ModelIR

    model_ir = G4ModelIR.model_validate(model_ir_dict)

    if not model_ir.sources:
        logger.warning("No sources in G4ModelIR — generating empty source")
        return {"code_modules": []}

    src = model_ir.sources[0]
    pdg_code = _PDG_MAP.get(src.particle_type.lower(), 2212)

    header = _generate_header(src)
    source = _generate_source(src, pdg_code)
    macro = _generate_macro(src)

    return {
        "code_modules": [{
            "module_name": "PrimaryGeneratorAction",
            "module_type": "source",
            "source_files": ["PrimaryGeneratorAction.cc"],
            "header_files": ["PrimaryGeneratorAction.hh"],
            "config_files": ["source.mac"],
            "depends_on": [],
            "linked_component_ids": [],
            "linked_material_ids": [],
            "generated_content": {
                "PrimaryGeneratorAction::PrimaryGeneratorAction.hh": header,
                "PrimaryGeneratorAction::PrimaryGeneratorAction.cc": source,
                "PrimaryGeneratorAction::source.mac": macro,
            },
        }],
    }


def _generate_header(src: Any) -> str:
    """Generate PrimaryGeneratorAction.hh."""
    return """// PrimaryGeneratorAction.hh
// Auto-generated by RadAgent source_codegen
// DO NOT EDIT — regenerate from G4ModelIR

#ifndef PRIMARY_GENERATOR_ACTION_HH
#define PRIMARY_GENERATOR_ACTION_HH

#include "G4VUserPrimaryGeneratorAction.hh"
#include "G4ParticleGun.hh"
#include "globals.hh"

class G4Event;

class PrimaryGeneratorAction : public G4VUserPrimaryGeneratorAction {
public:
    PrimaryGeneratorAction();
    ~PrimaryGeneratorAction() override;

    void GeneratePrimaries(G4Event* event) override;

    G4ParticleGun* GetParticleGun() const { return fParticleGun; }

private:
    G4ParticleGun* fParticleGun;
};

#endif
"""


def _generate_source(src: Any, pdg_code: int) -> str:
    """Generate PrimaryGeneratorAction.cc."""
    pos = src.beam.position
    direction = src.beam.direction
    energy_val = src.energy.value
    energy_unit = src.energy.unit

    # Map unit to Geant4 unit
    g4_unit = {"MeV": "MeV", "GeV": "GeV", "keV": "keV", "eV": "eV"}.get(
        energy_unit, "MeV"
    )

    evidence = "\n".join(
        f"// Evidence: {e}" for e in src.source_evidence
    )

    return f"""// PrimaryGeneratorAction.cc
// Auto-generated by RadAgent source_codegen
// DO NOT EDIT — regenerate from G4ModelIR
{evidence}

#include "PrimaryGeneratorAction.hh"
#include "G4Event.hh"
#include "G4ParticleGun.hh"
#include "G4ParticleTable.hh"
#include "G4ParticleDefinition.hh"
#include "G4SystemOfUnits.hh"
#include "G4PhysicalConstants.hh"

PrimaryGeneratorAction::PrimaryGeneratorAction()
    : G4VUserPrimaryGeneratorAction()
{{
    G4int n_particle = 1;
    fParticleGun = new G4ParticleGun(n_particle);

    // Particle definition (PDG = {pdg_code})
    auto* particleTable = G4ParticleTable::GetParticleTable();
    auto* particle = particleTable->FindParticle({pdg_code});
    fParticleGun->SetParticleDefinition(particle);

    // Energy: {energy_val} {energy_unit}
    fParticleGun->SetParticleEnergy({energy_val} * {g4_unit});

    // Position: [{pos[0]}, {pos[1]}, {pos[2]}] um
    fParticleGun->SetParticlePosition(
        G4ThreeVector({pos[0]}*um, {pos[1]}*um, {pos[2]}*um)
    );

    // Direction: [{direction[0]}, {direction[1]}, {direction[2]}]
    fParticleGun->SetParticleMomentumDirection(
        G4ThreeVector({direction[0]}, {direction[1]}, {direction[2]})
    );
}}

PrimaryGeneratorAction::~PrimaryGeneratorAction()
{{
    delete fParticleGun;
}}

void PrimaryGeneratorAction::GeneratePrimaries(G4Event* event)
{{
    fParticleGun->GeneratePrimaryVertex(event);
}}
"""


def _generate_macro(src: Any) -> str:
    """Generate source.mac for reference."""
    return f"""# source.mac
# Auto-generated by RadAgent source_codegen
# Reference macro — actual source configured in PrimaryGeneratorAction.cc

# Particle: {src.particle_type} (PDG {_PDG_MAP.get(src.particle_type.lower(), 2212)})
# Energy: {src.energy.value} {src.energy.unit} ({src.energy.distribution})
# Events: {src.events}
# Generator: {src.generator_type}
# Position: {src.beam.position}
# Direction: {src.beam.direction}
"""
