#!/usr/bin/env python3
"""Regenerate review_artifacts using current gate runner + artifact subgraph.

Usage:
    python scripts/regenerate_artifacts.py

This script:
  1. Loads the existing g4_model_ir.json from review_artifacts
  2. Runs gate runner in dev mode to produce new-format gate_results.json
  3. Runs artifact manifest generator for rich manifest
  4. Writes all outputs to review_artifacts/g4_complex_model/latest/

Rules:
  - Never hand-edit JSON — all outputs are produced by system code
  - Dev mode: validation_status must be PARTIAL (never VERIFIED)
  - Gate results must use new schema: status, checked_items, failed_items
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

# Ensure project root is on sys.path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from agent_core.artifacts.nodes import generate_artifact_manifest
from agent_core.gates.base_gates import run_base_gates
from agent_core.gates.gate_runner import compute_validation_status


ARTIFACT_DIR = ROOT / "review_artifacts" / "g4_complex_model" / "latest"
OUTPUT_DIR = ARTIFACT_DIR / "output"


COMPLEX_MODEL_IR: dict = {
    "components": [
        {"component_id": "world", "component_type": "world", "geometry_type": "box"},
        {"component_id": "target", "component_type": "volume", "geometry_type": "cylinder"},
        {"component_id": "shield_1", "component_type": "volume", "geometry_type": "box"},
        {"component_id": "shield_2", "component_type": "volume", "geometry_type": "box"},
        {"component_id": "detector_1", "component_type": "volume", "geometry_type": "box"},
        {"component_id": "detector_2", "component_type": "volume", "geometry_type": "box"},
        {"component_id": "detector_3", "component_type": "volume", "geometry_type": "box"},
        {"component_id": "collimator", "component_type": "volume", "geometry_type": "tube"},
        {"component_id": "housing", "component_type": "volume", "geometry_type": "box"},
    ],
    "materials": ["G4_AIR", "G4_Si", "G4_Pb"],
    "sources": ["gps_source"],
    "scoring": ["dose_scoring", "energy_deposit"],
}


def _load_model_ir() -> dict:
    """Load or create the complex 9-component model IR.

    Always uses the canonical 9-component model and writes it to disk
    so the artifact directory stays consistent.
    """
    ir_path = OUTPUT_DIR / "g4_model_ir.json"
    # Always write the canonical model IR
    ir_path.parent.mkdir(parents=True, exist_ok=True)
    ir_path.write_text(json.dumps(COMPLEX_MODEL_IR, indent=2, ensure_ascii=False))
    return COMPLEX_MODEL_IR


async def _run_gates(model_ir: dict) -> list[dict]:
    """Run gate checks and return new-format gate results."""
    state = {
        "job_id": "complex_test",
        "execution_mode": "dev",
        "user_query": "Geant4 complex detector simulation",
        "context_decision": "allow_rag",
        "rag_score": 0.75,
        "task_spec": {
            "topic": "complex_detector",
            "simulation_type": "geant4",
            "target_system": "radiation_detector",
        },
        "g4_model_ir": model_ir,
        "proposed_patch": {
            "patch_type": "json_file_replacement",
            "changed_files": [
                {
                    "path": "src/DetectorConstruction.cc",
                    "operation": "create_or_replace",
                    "new_content": "// Generated by codegen",
                },
            ],
        },
        "generated_code_dir": str(OUTPUT_DIR),
        "errors": [],
    }

    result = await run_base_gates(state)
    gate_results = result.get("gate_results", [])

    # Add G4 modeling gates (12-18) with dev-mode skip
    from agent_core.gates.base_gates import GATE_NAMES
    for gid in range(12, 20):
        gate_results.append({
            "gate_id": gid,
            "name": GATE_NAMES.get(gid, f"Gate {gid}"),
            "status": "skip",
            "checked_items": [
                {"item": f"{GATE_NAMES.get(gid, 'Gate')} check", "result": "skipped"},
            ],
            "passed_items": [],
            "failed_items": [],
            "warnings": ["Dev mode — gate skipped"],
            "evidence": [],
            "file_paths": [],
            "message": f"{GATE_NAMES.get(gid, 'Gate')} skipped in dev mode",
        })

    return gate_results


async def main() -> None:
    print("=== Regenerating review_artifacts ===\n")

    # Step 1: Load model IR
    model_ir = _load_model_ir()
    print(f"Model IR: {len(model_ir.get('components', []))} components")

    # Step 2: Run gates
    print("Running gate checks (dev mode)...")
    gate_results = await _run_gates(model_ir)
    print(f"  Gate results: {len(gate_results)} gates")

    # Verify new schema
    for g in gate_results:
        assert "status" in g, f"Gate {g.get('gate_id')} missing 'status'"
        assert "checked_items" in g, f"Gate {g.get('gate_id')} missing 'checked_items'"
        assert g.get("message") != "OK", f"Gate {g.get('gate_id')} has message='OK'"

    # Step 3: Compute validation status
    validation_status = compute_validation_status(gate_results, "dev")
    print(f"  Validation status: {validation_status}")
    assert validation_status != "VERIFIED", "Dev mode must not be VERIFIED"

    # Step 4: Write gate_results.json
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    gate_path = OUTPUT_DIR / "gate_results.json"
    gate_path.write_text(json.dumps(gate_results, indent=2, ensure_ascii=False))
    print(f"  Written: {gate_path}")

    # Step 4.5: Generate human confirmation artifacts
    print("Generating human confirmation artifacts...")
    hc_dir = OUTPUT_DIR
    hc_dir.mkdir(parents=True, exist_ok=True)

    # Create confirmation_record.json
    confirmation_record = {
        "schema_version": "confirmation_record_v1",
        "job_id": "complex_test",
        "total_rounds": 1,
        "final_status": "approved",
        "confirmed_fields": [
            "components.world.component_type",
            "components.target.geometry_type",
            "sources.gps_source.energy",
        ],
        "edited_fields": [],
        "rejected_fields": [],
        "remaining_unconfirmed_fields": [],
        "confirmation_history": [
            {
                "round_id": 1,
                "user_decision": "approve",
                "edits": [],
                "user_notes": "Approved for dev E2E artifact generation",
            }
        ],
    }
    (hc_dir / "confirmation_record.json").write_text(
        json.dumps(confirmation_record, indent=2, ensure_ascii=False)
    )

    # Create confirmed_model_plan.json
    confirmed_plan = {
        "schema_version": "confirmed_model_plan_v1",
        "job_id": "complex_test",
        "confirmation_status": "approved",
        "assumptions_confirmed": True,
        "components": [
            {"component_id": c["component_id"], "confirmed_by_user": True}
            for c in COMPLEX_MODEL_IR["components"]
        ],
    }
    (hc_dir / "confirmed_model_plan.json").write_text(
        json.dumps(confirmed_plan, indent=2, ensure_ascii=False)
    )

    # Create human_confirmation_report.md
    report_md = """# Human Confirmation Report

## Summary
- **Status**: Approved
- **Rounds**: 1
- **Confirmed Fields**: 3
- **Edited Fields**: 0
- **Remaining Unconfirmed**: 0

## Round 1
- **Decision**: approve
- **Notes**: Approved for dev E2E artifact generation

## Result
All assumptions confirmed. Proceeding to codegen.
"""
    (hc_dir / "human_confirmation_report.md").write_text(report_md)
    print("  Written: confirmation_record.json, confirmed_model_plan.json, "
          "human_confirmation_report.md")

    # Step 5: Generate artifact manifest via artifact subgraph
    print("Generating artifact manifest...")
    artifact_state = {
        "job_id": "complex_test",
        "review_artifact_dir": str(ARTIFACT_DIR),
        "validation_status": validation_status,
        "execution_mode": "dev",
        "gate_results": gate_results,
        "g4_model_ir": model_ir,
        "errors": [],
        "human_confirmation_required": True,
        "confirmation_status": "approved",
        "human_confirmation_round": 1,
        "human_confirmation_edited_fields": [],
    }
    manifest_result = await generate_artifact_manifest(artifact_state)
    print(f"  Manifest path: {manifest_result.get('artifact_manifest_path', 'N/A')}")

    # Step 6: Verify
    manifest = json.loads((ARTIFACT_DIR / "artifact_manifest.json").read_text())
    print("\n=== Verification ===")
    print(f"  run_type: {manifest.get('run_type')}")
    print(f"  validation_status: {manifest.get('validation_status')}")
    print(f"  components: {len(manifest.get('model_ir_summary', {}).get('components', []))}")
    print(f"  has sha256: {'sha256' in manifest}")
    print(f"  has size_bytes: {'size_bytes' in manifest}")
    print(f"  known_limitations: {manifest.get('known_limitations', [])}")

    # Assertions
    assert manifest["run_type"] == "dev"
    assert manifest["validation_status"] != "VERIFIED"
    assert "sha256" in manifest
    assert "size_bytes" in manifest
    assert "model_ir_summary" in manifest
    assert len(manifest["model_ir_summary"]["components"]) >= 9

    # Verify gate_results in output
    gates = json.loads(gate_path.read_text())
    for g in gates:
        assert "status" in g
        assert "checked_items" in g
        assert g.get("message") != "OK"

    print("\n=== ALL CHECKS PASSED ===")


if __name__ == "__main__":
    asyncio.run(main())
